[package]
name = "numlex"
version = "3.1.0"
description = "Numlex — notepad based calculator"
authors = ["Qulierm <nikita.gostevsky@gmail.com>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls-webpki-roots"], default-features = false }
tokio = { version = "1", features = ["rt", "time"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
