import Foundation
import CryptoKit

// MARK: - Bundled public-holiday catalog (temporal Task 5)
//
// A reproducible, offline-only public-holiday profile set. The bundled
// `holidays.tsv` is generated by `Scripts/generate-holiday-data.py` from
// deterministic rule tables (fixed dates, nth-weekday rules and the
// Gregorian Easter computus) for a fixed country set and year range; the
// `sources.json` manifest records the generator, version, year coverage,
// license/attribution and the SHA-256 of the data, which this loader
// VERIFIES — a truncated or edited file can never load. No runtime
// network access exists anywhere in this path.

public struct HolidayCatalog: Sendable {
    public enum LoadError: Error, Equatable {
        case missingResource(String)
        case integrityFailure(String)
        case malformed(String)
    }

    /// The bundled set (nil when the resource bundle is unavailable).
    public static let shared: HolidayCatalog? = HolidayCatalog.embedded()

    /// `CC|yyyy-MM-dd` keys.
    private let holidays: Set<String>
    private let countryYears: [String: Set<Int>]
    /// The generated year coverage (closed range).
    public let yearRange: ClosedRange<Int>
    public let version: String
    public let attribution: String
    public let license: String
    /// Sorted ISO country codes.
    public let countries: [String]

    // MARK: loading

    public static func embedded() -> HolidayCatalog? {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle.main
        #endif
        guard let directory = bundle.url(forResource: "NumlexHolidays", withExtension: nil)
                ?? bundle.resourceURL?.appendingPathComponent("NumlexHolidays") else {
            return nil
        }
        return try? HolidayCatalog(contentsOf: directory)
    }

    /// The committed resource directory as it exists in the build products
    /// (used by tests; `embedded()` uses the SwiftPM bundle accessor).
    public static var builtResourceDirectory: URL? {
        let candidates = [
            Bundle.main.resourceURL,
            URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
                .appendingPathComponent(".build/arm64-apple-macosx/debug"),
            URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
                .appendingPathComponent(".build/debug"),
        ]
        for base in candidates {
            guard let base else { continue }
            let direct = base.appendingPathComponent("NumlexHolidays")
            if FileManager.default.fileExists(atPath: direct.path) { return direct }
            let nested = base.appendingPathComponent("Numlex_NumlexCore.bundle")
                .appendingPathComponent("NumlexHolidays")
            if FileManager.default.fileExists(atPath: nested.path) { return nested }
        }
        return nil
    }

    /// Testable loader: verifies `holidays.tsv` against the manifest
    /// SHA-256, then parses the country/year coverage.
    public init(contentsOf directory: URL) throws {
        let dataURL = directory.appendingPathComponent("holidays.tsv")
        let manifestURL = directory.appendingPathComponent("sources.json")
        guard let data = try? Data(contentsOf: dataURL) else {
            throw LoadError.missingResource("holidays.tsv")
        }
        guard let manifestData = try? Data(contentsOf: manifestURL),
              let manifest = try? JSONSerialization.jsonObject(with: manifestData) as? [String: Any] else {
            throw LoadError.missingResource("sources.json")
        }
        let resources = manifest["resources"] as? [String: [String: String]]
        guard let expected = resources?["holidays.tsv"]?["sha256"] else {
            throw LoadError.integrityFailure("holidays.tsv")
        }
        let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        guard digest == expected else {
            throw LoadError.integrityFailure("holidays.tsv")
        }
        version = manifest["version"] as? String ?? "unknown"
        attribution = manifest["attribution"] as? String ?? ""
        license = manifest["license"] as? String ?? ""
        if let range = manifest["yearRange"] as? [Int], range.count == 2 {
            yearRange = range[0]...range[1]
        } else if let counts = manifest["countries"] as? [String: Int], !counts.isEmpty {
            yearRange = 0...9999
        } else {
            throw LoadError.malformed("yearRange")
        }
        var parsed: Set<String> = []
        var years: [String: Set<Int>] = [:]
        let text = String(decoding: data, as: UTF8.self)
        for rawLine in text.split(separator: "\n", omittingEmptySubsequences: true) {
            let line = String(rawLine)
            if line.hasPrefix("#") { continue }
            let fields = line.split(separator: "\t", omittingEmptySubsequences: false)
            guard fields.count >= 2 else { continue }
            let country = String(fields[0]).uppercased()
            let parts = fields[1].split(separator: "-")
            guard parts.count == 3, let year = Int(parts[0]),
                  let month = Int(parts[1]), let day = Int(parts[2]) else { continue }
            parsed.insert("\(country)|\(parts[0])-\(String(format: "%02d", month))-\(String(format: "%02d", day))")
            years[country, default: []].insert(year)
        }
        guard !parsed.isEmpty else { throw LoadError.malformed("holidays.tsv") }
        self.holidays = parsed
        self.countryYears = years
        self.countries = years.keys.sorted()
    }

    /// A testable in-memory catalog (dates as ISO strings).
    public init(countries: [String: Set<String>],
                yearRange: ClosedRange<Int>,
                version: String = "test",
                attribution: String = "test",
                license: String = "test") {
        var parsed: Set<String> = []
        var years: [String: Set<Int>] = [:]
        for (country, dates) in countries {
            let cc = country.uppercased()
            for iso in dates {
                parsed.insert("\(cc)|\(iso)")
                if let year = Int(iso.prefix(4)) { years[cc, default: []].insert(year) }
            }
        }
        self.holidays = parsed
        self.countryYears = years
        self.yearRange = yearRange
        self.version = version
        self.attribution = attribution
        self.license = license
        self.countries = years.keys.sorted()
    }

    // MARK: lookup

    public func isSupported(_ country: String) -> Bool {
        countryYears[country.uppercased()] != nil
    }

    public func supports(country: String, year: Int) -> Bool {
        countryYears[country.uppercased()]?.contains(year) == true
    }

    public func isHoliday(country: String, year: Int, month: Int, day: Int) -> Bool {
        let key = "\(country.uppercased())|\(String(format: "%04d-%02d-%02d", year, month, day))"
        return holidays.contains(key)
    }

    /// The holiday count for one country (diagnostics/tests).
    public func holidayCount(_ country: String) -> Int {
        let prefix = "\(country.uppercased())|"
        return holidays.reduce(0) { $0 + ($1.hasPrefix(prefix) ? 1 : 0) }
    }
}
