import Foundation

public struct L10n {
    public static func t(_ key: String, language: AppLanguage) -> String {
        let table = translations[language] ?? translations[.en]!
        return table[key] ?? translations[.en]![key] ?? key
    }

    public static let translations: [AppLanguage: [String: String]] = [
        .en: [
            // r87: number formatting (menu + Numbers settings + Format menu)
            "numbers.format": "Default answer format",
            "numbers.formatCap": "How numeric answers are shown and copied. Calculation precision is never changed.",
            "notation.label": "Notation",
            "negative.label": "Negative numbers",
            "negative.minus": "Minus prefix (-123)",
            "negative.parentheses": "Parentheses (123)",
            "negative.trailingMinus": "Trailing minus (123-)",
            "currency.label": "Currency symbol",
            "currency.before": "Before ($123)",
            "currency.beforeSpaced": "Before, spaced ($ 123)",
            "currency.after": "After (123$)",
            "currency.afterSpaced": "After, spaced (123 $)",
            "negative.cap": "How negative results are shown.",
"currency.cap": "Where the currency symbol sits.",
            "fraction.label": "Fraction denominator",
            "fraction.cap": "The largest denominator the fraction approximation may use.",
            "customPattern.label": "Custom format",
            "customPattern.cap": "A number skeleton like #,##0.00: # is a digit (zero optional), 0 a required digit. Up to 96 characters.",
            "customPattern.invalid": "Pattern is invalid - answers use the automatic format until it is fixed.",
            "customPattern.preview": "Preview",
            "numberFormat": "Number Format",
            "formatDefault": "Default",
            "formatAutomatic": "Automatic",
            "formatDecimal": "Decimal",
            "formatScientific": "Scientific",
            "formatEngineering": "Engineering",
            "formatFraction": "Fraction",
            "formatTimespan": "Timespan",
            "formatCustom": "Custom",
            "customPatternInvalid": "Set a valid custom pattern in Settings to use Custom.",
            "resetFormatting": "Reset Formatting to Defaults",
            "highlight": "Highlight",
            "highlightNone": "None",
            "highlightYellow": "Yellow",
            "highlightOrange": "Orange",
            "highlightGreen": "Green",
            "highlightBlue": "Blue",
            "highlightPurple": "Purple",
            "highlightPink": "Pink",
            "styling.column": "Answer column",
            "styling.columnCap": "How the answer column is filled and where answers sit in it.",
            "styling.column.alignment": "Alignment",
            "alignment.leading": "Leading",
            "alignment.trailing": "Trailing",
            "styling.column.surface": "Background",
            "surface.neutral": "Neutral",
            "surface.sand": "Sand",
            "surface.slate": "Slate",
            "surface.sage": "Sage",
            "surface.blush": "Blush",
            "settings.numbers": "Numbers",
            "settings.datesTimes": "Dates & Times",
            "settings.datesTimesShort": "Dates",
            "datesTimes.work": "Work calendar",
            "holidayRegion.label": "Holiday region",
            "holidayRegion.automatic": "Automatic (system region)",
            "holidayRegion.cap": "Workdays skip public holidays of the selected region. Unsupported regions fail in dated workday queries.",
            "hoursPerWorkday.label": "Hours per workday",
            "hoursPerWorkday.cap": "Used by work hours and workday conversions. Between 1 and 24.",
            "timezones.group": "Custom timezones",
            "timezones.intro": "Name a timezone you use often and ask for it by name — for example, time in HQ. Only active rows are available in sheets.",
            "timezones.add": "Add Timezone",
            "timezones.name": "Name",
            "timezones.identifier": "IANA identifier",
            "timezones.delete": "Delete timezone",
            "timezones.emptyTitle": "No custom timezones",
            "timezones.emptyCap": "Add an alias for a timezone you use often, then ask for it by name in any sheet.",
            "timezones.status.active": "Active",
            "timezones.status.incomplete": "Enter a name and an identifier",
            "timezones.status.invalidName": "Invalid name",
            "timezones.status.duplicate": "Duplicate name",
            "timezones.status.builtInCollision": "Reserved by a built-in place",
            "timezones.status.unknownZone": "Unknown timezone",
            "settings.format": "Format",
            "numbers.region": "Number format",
            "numbers.regionLabel": "Region",
            "numbers.sample": "Example",
            "numbers.syntax": "Function arguments",
            "numbers.convertPaste": "Convert foreign numbers on paste",
            "numbers.convertPasteCap": "Paste of 1,234.56 becomes the local form, e.g. 1.234,56. Prose and already-local numbers are left untouched.",
            "numbers.grouping": "Show thousands separator",
            "numbers.groupingCap": "10000 displays as 10,000 (or the local form)",
            "numbers.compact": "Compact large numbers",
            "numbers.compactCap": "100000 displays as 100k. Copied values keep full precision.",
            "numbers.confirmTitle": "Change number format?",
            "numbers.confirmBody": "Changing the region can re-interpret the numbers in this sheet. Answers that change:",
            "numbers.apply": "Apply",
            "numbers.cancel": "Cancel",
            "sheet": "Sheet",
            "empty": "Empty",
            "line": "line",
            "lines": "lines",
            "noLines": "No lines",
            "newSheet": "New Sheet",
            "deleteSheet": "Delete sheet",
            "folderGeneral": "General",
            "newFolder": "New Folder",
            "renameFolder": "Rename Folder",
            "deleteFolder": "Delete Folder",
            "deleteFolderHelp": "The sheets in this folder are moved to General — no sheet is deleted.",
            "moveToFolder": "Move to Folder",
            "newSheetInFolder": "New Sheet in Folder",
            "dropSheetHere": "Drop a sheet here to move it",
            "folderEmpty": "No sheets",
            "sheets": "Sheets",
            "showSheets": "Show sheets",
            "hideSheets": "Hide sheets",
            "importSheet": "Import sheet (.nlx)",
            "exportSheet": "Export sheet (.nlx)",
            "enter": "Enter an expression to start",
            "settings": "Settings",
            "total": "Total",
            "copyAnswer": "Copy Answer",
            "deleteLine": "Delete Line",
            "rounding": "Rounding",
            "roundingDefault": "Default",
            "editAnswerFormatting": "Edit answer formatting",
            "decimalPlaces": "decimal places",
            "weatherUnavailable": "Weather unavailable",
            "locationUnavailable": "Location unavailable",
            "rename": "Rename",
            "round": "Rounding numbers:",
            "fontcolor": "Font color:",
            "fontsize": "Font size:",
            "sheetname": "Sheet title:",
            "language": "Interface language:",
            "linenumber": "Line numbers:",
            "hideSidebarBtn": "Hide sidebar button when collapsed",
            "hideSidebarBtnCap": "Use ⌃⌘S (Control-Command-S) to show the sidebar",
            "showTotalBar": "Show total bar",
            "appearance": "Appearance:",
            "appearanceLight": "Light",
            "appearanceDark": "Dark",
            "appearanceAuto": "Auto",
            "settings.about": "About",
            "about.documentation": "Documentation",
            "about.version": "Version %@",
            "settings.aboutShort": "About",
            "settings.updates": "Updates",
            "settings.constantsUnits": "Constants & Units",
            "settings.constantsUnitsShort": "Constants",
            "appIcon": "Application icon:",
            "appIconDark": "Dark",
            "appIconLight": "Light",
            "operators": "Operators",
            "opPad": "Pad operators with spaces",
            "opPadCap": "1+1 becomes 1 + 1",
            "opStar": "Replace * with ×",
            "opStarCap": "3*3 becomes 3 × 3",
            "opBacktick": "Replace backtick ` with +",
            "opBacktickCap": "5`5 becomes 5 + 5",
            "opQuick": "Use QuickOperators",
            "opQuickCap": "5p5 becomes 5 + 5, 5m5 becomes 5 − 5\n5x5 becomes 5 × 5, 5d5 becomes 5 ÷ 5",
            "autoInsert": "Automatic Insertions",
            "autoGroup": "Format numbers with thousand separators",
            "autoGroupCap": "Groups the numbers you type as you type (10000 becomes 10,000).",
            "autoPrev": "Insert previous answer after typing operator on new line",
            "autoPrevCap": "After pressing return, type any operator (+ − × or ÷)",
            "settings.general": "General",
            "welcome.getStarted": "Get Started",
            "welcome.getStartedHint": "Opens the notebook",
            "settings.constants": "Constants",
            "constants.intro": "Available in every sheet. .nlx exports never embed constants.",
            "constants.emptyTitle": "No constants",
            "constants.emptyCap": "Constants become available in every sheet. .nlx exports never embed them.",
            "units.emptyTitle": "No custom units",
            "units.emptyCap": "A definition is `12 feet` (a multiple of an existing unit) or `new unit` (an independent dimension).",
            "units.tab.constants": "Constants",
            "units.tab.units": "Units",
            "units.intro": "Available in every sheet. .nlx exports never embed units. A definition is `12 feet` (a multiple of an existing unit) or `new unit` (an independent dimension).",
            "units.name": "Name",
            "units.definition": "Definition",
            "units.add": "Add Unit",
            "units.delete": "Delete unit",
            "units.newUnit": "new unit",
            "units.statusActive": "Active",
            "units.statusEmpty": "Empty",
            "units.statusIncomplete": "Name or definition missing",
            "units.statusInvalidName": "Invalid name",
            "units.statusDuplicate": "Duplicate name",
            "units.statusBuiltIn": "Name is a built-in unit",
            "units.statusConstant": "Name is a constant",
            "units.statusInvalidDefinition": "Invalid definition",
            "units.statusUnknown": "Unknown unit in definition",
            "units.statusCycle": "Circular definition",
            "units.statusNonFinite": "Definition is not a positive finite number",
            "units.statusLimit": "Beyond the 100-unit limit",
            "constants.name": "Name",
            "constants.value": "Value",
            "constants.add": "Add Constant",
            "constants.delete": "Delete constant",
            "constants.incomplete": "Name or value missing",
            "constants.invalidName": "Name: 1–6 words, letters A–Z",
            "constants.duplicate": "Duplicate name",
            "constants.reserved": "Name is reserved",
            "constants.invalidExpression": "Invalid value",
            "constants.invalidDependency": "Unknown name in value",
            "constants.cycle": "Circular reference",
            "constants.exceedsLimit": "Row limit reached",
            "settings.styling": "Styling",
            "settings.stylingShort": "Style",
            "settings.editing": "Editing",
            "general.interface": "Interface",
            "general.notebook": "Notebook",
            "numbers.answer": "Answer display",
            "numbers.pasting": "Pasting",
            "styling.typography": "Typography",
            "styling.colors": "Syntax colors",
            "styling.colorsCap": "Preset or custom colors for each notebook role. The default action restores a role's factory preset.",
            "styling.colors.custom": "Custom",
            "styling.colors.default": "Default",
            "styling.colors.resetRole": "Restore the default color for this role",
            "styling.colors.resetAll": "Reset Syntax Colors",
            "styling.colors.resetAllCap": "Restores the default syntax colors. Font and answer column settings are kept.",
            "styling.colors.pick": "Pick a custom color for this role",
            "roundingCap": "Answers are rounded to this many decimal places.",
            "styling.fontsize": "Font size:",
            "styling.font": "Font:",
            "styling.font.system": "System Default",
            "styling.font.rounded": "Rounded",
            "styling.font.serif": "Serif",
            "styling.font.monospaced": "Monospaced",
            "styling.color.standardText": "Standard Text",
            "styling.color.cyan": "Cyan",
            "styling.color.green": "Green",
            "styling.color.pinkPurple": "Pink Purple",
            "styling.color.blue": "Blue",
            "styling.color.moneyPurple": "Money Purple",
            "styling.role.numbers": "Numbers",
            "styling.role.operators": "Operators",
            "styling.role.variables": "Variables",
            "styling.role.units": "Units",
            "styling.role.specifiers": "Specifiers",
            "styling.role.headings": "Headings",
            "styling.role.comments": "Comments",
            "styling.role.labels": "Labels",
            "styling.preview": "Preview",
            "updates.group": "Updates",
            "updates.checkNow": "Check for Updates…",
            "updates.checkNowShort": "Check Now",
            "updates.auto": "Automatically check for updates",
            "updates.autoCap": "Numlex checks for a new version in the background and asks before installing it.",
            "updates.unavailable": "Updates are unavailable in this build.",
            "updates.unavailable.notPackaged": "This development build is not a packaged app, so updates are disabled.",
            "updates.unavailable.missingFeedURL": "This build has no update feed configured, so updates are disabled.",
            "updates.unavailable.insecureFeedURL": "The update feed URL is not a secure HTTPS address, so updates are disabled.",
            "updates.unavailable.missingPublicKey": "This build has no update verification key, so updates are disabled.",
            "updates.unavailable.invalidPublicKey": "The update verification key in this build is invalid, so updates are disabled.",
        ],
        .ru: [
            "settings.numbers": "Числа",
            "settings.datesTimes": "Дата и время",
            "settings.datesTimesShort": "Дата",
            "datesTimes.work": "Рабочий календарь",
            "holidayRegion.label": "Праздничный регион",
            "holidayRegion.automatic": "Автоматически (регион системы)",
            "holidayRegion.cap": "Рабочие дни не учитывают государственные праздники выбранного региона. Неподдерживаемые регионы дают ошибку в запросах по датам.",
            "hoursPerWorkday.label": "Часов в рабочем дне",
            "hoursPerWorkday.cap": "Используется для рабочих часов и пересчёта рабочих дней. От 1 до 24.",
            "timezones.group": "Свои часовые пояса",
            "timezones.intro": "Дайте название часовому поясу, которым часто пользуетесь, и спрашивайте его по имени — например, time in Офис. В листах доступны только активные строки.",
            "timezones.add": "Добавить пояс",
            "timezones.name": "Название",
            "timezones.identifier": "Идентификатор IANA",
            "timezones.delete": "Удалить пояс",
            "timezones.emptyTitle": "Нет своих часовых поясов",
            "timezones.emptyCap": "Добавьте псевдоним для часто используемого часового пояса и спрашивайте его по имени в любом листе.",
            "timezones.status.active": "Активен",
            "timezones.status.incomplete": "Введите название и идентификатор",
            "timezones.status.invalidName": "Недопустимое название",
            "timezones.status.duplicate": "Название повторяется",
            "timezones.status.builtInCollision": "Занято встроенным местом",
            "timezones.status.unknownZone": "Неизвестный часовой пояс",
            "settings.format": "Формат",
            "numbers.region": "Формат чисел",
            "numbers.regionLabel": "Регион",
            "numbers.sample": "Пример",
            "numbers.syntax": "Аргументы функций",
            "numbers.convertPaste": "Преобразовать иностранные числа при вставке",
            "numbers.convertPasteCap": "Вставленное 1,234.56 станет локальной формой, например 1 234,56. Текст и локальные числа не меняются.",
            "numbers.grouping": "Показывать разделитель тысяч",
            "numbers.groupingCap": "10000 отображается как 10 000 (или в локальной форме)",
            "numbers.compact": "Компактно показывать большие числа",
            "numbers.compactCap": "100000 отображается как 100k. Скопированные значения сохраняют точность.",
            "numbers.confirmTitle": "Сменить формат чисел?",
            "numbers.confirmBody": "Смена региона может переинтерпретировать числа в этом листе. Меняющиеся ответы:",
            "numbers.apply": "Применить",
            "numbers.cancel": "Отмена",
            // r87: number formatting
            "numbers.format": "Формат ответов по умолчанию",
            "numbers.formatCap": "Как показываются и копируются числовые ответы. Точность вычислений не меняется.",
            "notation.label": "Запись",
            "negative.label": "Отрицательные числа",
            "negative.minus": "Минус в начале (-123)",
            "negative.parentheses": "Скобки (123)",
            "negative.trailingMinus": "Минус в конце (123-)",
            "currency.label": "Знак валюты",
            "currency.before": "Спереди ($123)",
            "currency.beforeSpaced": "Спереди с пробелом ($ 123)",
            "currency.after": "Сзади (123$)",
            "currency.afterSpaced": "Сзади с пробелом (123 $)",
            "negative.cap": "Как показываются отрицательные результаты.",
"currency.cap": "Расположение знака валюты.",
            "fraction.label": "Знаменатель дроби",
            "fraction.cap": "Наибольший знаменатель для приближения дробью.",
            "customPattern.label": "Свой формат",
            "customPattern.cap": "Шаблон числа, например #,##0.00: # — цифра (ноль опционален), 0 — обязательная цифра. До 96 символов.",
            "customPattern.invalid": "Шаблон неверен — ответы показываются в автоматическом формате, пока он не исправлен.",
            "customPattern.preview": "Предпросмотр",
            "numberFormat": "Формат числа",
            "formatDefault": "По умолчанию",
            "formatAutomatic": "Автоматически",
            "formatDecimal": "Десятичный",
            "formatScientific": "Научный",
            "formatEngineering": "Инженерный",
            "formatFraction": "Дробь",
            "formatTimespan": "Промежуток",
            "formatCustom": "Свой",
            "customPatternInvalid": "Укажите корректный шаблон в настройках, чтобы использовать «Свой».",
            "resetFormatting": "Сбросить форматирование",
            "highlight": "Подсветка",
            "highlightNone": "Нет",
            "highlightYellow": "Жёлтый",
            "highlightOrange": "Оранжевый",
            "highlightGreen": "Зелёный",
            "highlightBlue": "Синий",
            "highlightPurple": "Фиолетовый",
            "highlightPink": "Розовый",
            "styling.column": "Колонка ответов",
            "styling.columnCap": "Фон колонки ответов и расположение ответов в ней.",
            "styling.column.alignment": "Выравнивание",
            "alignment.leading": "Слева",
            "alignment.trailing": "Справа",
            "styling.column.surface": "Фон",
            "surface.neutral": "Нейтральный",
            "surface.sand": "Песок",
            "surface.slate": "Серый",
            "surface.sage": "Шалфей",
            "surface.blush": "Розовый",
            "sheet": "Лист",
            "empty": "Пусто",
            "line": "строка",
            "lines": "строки",
            "noLines": "Нет строк",
            "newSheet": "Новый лист",
            "deleteSheet": "Удалить лист",
            "folderGeneral": "Общие",
            "newFolder": "Новая папка",
            "renameFolder": "Переименовать папку",
            "deleteFolder": "Удалить папку",
            "deleteFolderHelp": "Листы из этой папки будут перемещены в «Общие» — ни один лист не удаляется.",
            "moveToFolder": "Переместить в папку",
            "newSheetInFolder": "Новый лист в папке",
            "dropSheetHere": "Перетащите лист сюда, чтобы переместить его",
            "folderEmpty": "Нет листов",
            "sheets": "Листы",
            "showSheets": "Показать листы",
            "hideSheets": "Скрыть листы",
            "importSheet": "Импорт листа (.nlx)",
            "exportSheet": "Экспорт листа (.nlx)",
            "enter": "Введите выражение чтобы начать",
            "settings": "Настройки",
            "total": "Итого",
            "copyAnswer": "Копировать ответ",
            "deleteLine": "Удалить строку",
            "rounding": "Округление",
            "roundingDefault": "По умолчанию",
            "editAnswerFormatting": "Изменение формата ответа",
            "decimalPlaces": "знаков после запятой",
            "weatherUnavailable": "Погода недоступна",
            "locationUnavailable": "Местоположение недоступно",
            "rename": "Переименовать",
            "round": "Округление чисел:",
            "fontcolor": "Цвет текста:",
            "fontsize": "Размер текста:",
            "sheetname": "Заголовок листов:",
            "language": "Язык интерфейса:",
            "linenumber": "Номера строк",
            "hideSidebarBtn": "Скрывать кнопку боковой панели после сворачивания",
            "hideSidebarBtnCap": "Чтобы открыть боковую панель, нажмите ⌃⌘S (Control-Command-S)",
            "showTotalBar": "Показывать панель итога",
            "appearance": "Оформление:",
            "appearanceLight": "Светлое",
            "appearanceDark": "Тёмное",
            "appearanceAuto": "Авто",
            "settings.about": "О программе",
            "about.documentation": "Документация",
            "about.version": "Версия %@",
            "settings.aboutShort": "Сведения",
            "settings.updates": "Обновления",
            "settings.constantsUnits": "Константы и единицы",
            "settings.constantsUnitsShort": "Константы",
            "appIcon": "Значок приложения:",
            "appIconDark": "Тёмный",
            "appIconLight": "Светлый",
            "operators": "Операторы",
            "opPad": "Отступы вокруг операторов",
            "opPadCap": "1+1 станет 1 + 1",
            "opStar": "Заменять * на ×",
            "opStarCap": "3*3 станет 3 × 3",
            "opBacktick": "Заменять обратную кавычку ` на +",
            "opBacktickCap": "5`5 станет 5 + 5",
            "opQuick": "Использовать QuickOperators",
            "opQuickCap": "5p5 станет 5 + 5, 5m5 станет 5 − 5\n5x5 станет 5 × 5, 5d5 станет 5 ÷ 5",
            "autoInsert": "Автоматические вставки",
            "autoGroup": "Разделители тысяч в числах",
            "autoGroupCap": "Группирует числа при вводе (10000 становится 10 000).",
            "autoPrev": "Вставлять предыдущий ответ после оператора на новой строке",
            "autoPrevCap": "После нажатия Return введите оператор (+ − × или ÷)",
            "settings.general": "Основные",
            "welcome.getStarted": "Начать",
            "welcome.getStartedHint": "Открывает блокнот",
            "settings.constants": "Константы",
            "constants.intro": "Доступны во всех листах. .nlx-файлы не содержат константы.",
            "constants.emptyTitle": "Нет констант",
            "constants.emptyCap": "Константы становятся доступны во всех листах. Экспорты .nlx не содержат их.",
            "units.emptyTitle": "Нет собственных единиц",
            "units.emptyCap": "Определение — `12 feet` (кратная существующей единице) или `new unit` (независимая размерность).",
            "units.tab.constants": "Константы",
            "units.tab.units": "Единицы",
            "units.intro": "Доступны во всех листах. .nlx-файлы не содержат единицы. Определение — `12 feet` (кратная существующей единице) или `new unit` (независимая размерность).",
            "units.name": "Имя",
            "units.definition": "Определение",
            "units.add": "Добавить единицу",
            "units.delete": "Удалить единицу",
            "units.newUnit": "new unit",
            "units.statusActive": "Действует",
            "units.statusEmpty": "Пусто",
            "units.statusIncomplete": "Нет имени или определения",
            "units.statusInvalidName": "Неверное имя",
            "units.statusDuplicate": "Повтор имени",
            "units.statusBuiltIn": "Имя совпадает со встроенной единицей",
            "units.statusConstant": "Имя совпадает с константой",
            "units.statusInvalidDefinition": "Неверное определение",
            "units.statusUnknown": "Неизвестная единица в определении",
            "units.statusCycle": "Циклическое определение",
            "units.statusNonFinite": "Определение не является положительным конечным числом",
            "units.statusLimit": "Превышен лимит в 100",
            "constants.name": "Имя",
            "constants.value": "Значение",
            "constants.add": "Добавить константу",
            "constants.delete": "Удалить константу",
            "constants.incomplete": "Не указано имя или значение",
            "constants.invalidName": "Имя: 1–6 слов, буквы A–Z",
            "constants.duplicate": "Дублирующееся имя",
            "constants.reserved": "Имя зарезервировано",
            "constants.invalidExpression": "Недопустимое значение",
            "constants.invalidDependency": "Неизвестное имя в значении",
            "constants.cycle": "Циклическая ссылка",
            "constants.exceedsLimit": "Превышен лимит строк",
            "settings.styling": "Оформление",
            "settings.stylingShort": "Стиль",
            "settings.editing": "Правка",
            "general.interface": "Интерфейс",
            "general.notebook": "Блокнот",
            "numbers.answer": "Отображение ответов",
            "numbers.pasting": "Вставка",
            "styling.typography": "Типографика",
            "styling.colors": "Цвета синтаксиса",
            "styling.colorsCap": "Пресетовые или пользовательские цвета для каждой роли. Действие «По умолчанию» возвращает заводской пресет роли.",
            "styling.colors.custom": "Пользовательский",
            "styling.colors.default": "По умолчанию",
            "styling.colors.resetRole": "Восстановить цвет по умолчанию для этой роли",
            "styling.colors.resetAll": "Сбросить цвета синтаксиса",
            "styling.colors.resetAllCap": "Возвращает цвета синтаксиса к значениям по умолчанию. Настройки шрифта и колонки ответов сохраняются.",
            "styling.colors.pick": "Выбрать цвет для этой роли",
            "roundingCap": "Ответы округляются до этого количества десятичных знаков.",
            "styling.fontsize": "Размер шрифта:",
            "styling.font": "Шрифт:",
            "styling.font.system": "Системный",
            "styling.font.rounded": "Округлённый",
            "styling.font.serif": "С засечками",
            "styling.font.monospaced": "Моноширинный",
            "styling.color.standardText": "Основной текст",
            "styling.color.cyan": "Бирюзовый",
            "styling.color.green": "Зелёный",
            "styling.color.pinkPurple": "Розово-фиолетовый",
            "styling.color.blue": "Синий",
            "styling.color.moneyPurple": "Фиолетовый",
            "styling.role.numbers": "Числа",
            "styling.role.operators": "Операторы",
            "styling.role.variables": "Переменные",
            "styling.role.units": "Единицы",
            "styling.role.specifiers": "Связки",
            "styling.role.headings": "Заголовки",
            "styling.role.comments": "Комментарии",
            "styling.role.labels": "Подписи",
            "styling.preview": "Предпросмотр",
            "updates.group": "Обновления",
            "updates.checkNow": "Проверить обновления…",
            "updates.checkNowShort": "Проверить",
            "updates.auto": "Проверять обновления автоматически",
            "updates.autoCap": "Numlex проверяет наличие новой версии в фоне и спрашивает перед установкой.",
            "updates.unavailable": "В этой сборке обновления недоступны.",
            "updates.unavailable.notPackaged": "Это сборка для разработки без пакета приложения, поэтому обновления отключены.",
            "updates.unavailable.missingFeedURL": "В этой сборке не настроен канал обновлений, поэтому обновления отключены.",
            "updates.unavailable.insecureFeedURL": "Адрес канала обновлений не защищён HTTPS, поэтому обновления отключены.",
            "updates.unavailable.missingPublicKey": "В этой сборке нет ключа проверки обновлений, поэтому обновления отключены.",
            "updates.unavailable.invalidPublicKey": "Ключ проверки обновлений в этой сборке некорректен, поэтому обновления отключены.",
        ],
        .de: [
            "settings.numbers": "Zahlen",
            "settings.datesTimes": "Datum & Uhrzeit",
            "settings.datesTimesShort": "Datum",
            "datesTimes.work": "Arbeitskalender",
            "holidayRegion.label": "Feiertagsregion",
            "holidayRegion.automatic": "Automatisch (Systemregion)",
            "holidayRegion.cap": "Arbeitstage überspringen Feiertage der gewählten Region. Nicht unterstützte Regionen liefern bei datierten Abfragen einen Fehler.",
            "hoursPerWorkday.label": "Stunden pro Arbeitstag",
            "hoursPerWorkday.cap": "Wird für Arbeitsstunden und Arbeitstage-Umrechnungen genutzt. Zwischen 1 und 24.",
            "timezones.group": "Eigene Zeitzonen",
            "timezones.intro": "Geben Sie einer häufig genutzten Zeitzone einen Namen und fragen Sie sie per Namen ab — z. B. time in Büro. Nur aktive Zeilen sind in Blättern verfügbar.",
            "timezones.add": "Zeitzone hinzufügen",
            "timezones.name": "Name",
            "timezones.identifier": "IANA-Kennung",
            "timezones.delete": "Zeitzone löschen",
            "timezones.emptyTitle": "Keine eigenen Zeitzonen",
            "timezones.emptyCap": "Fügen Sie einen Alias für eine häufig genutzte Zeitzone hinzu und fragen Sie ihn in jedem Blatt per Namen ab.",
            "timezones.status.active": "Aktiv",
            "timezones.status.incomplete": "Name und Kennung eingeben",
            "timezones.status.invalidName": "Ungültiger Name",
            "timezones.status.duplicate": "Doppelter Name",
            "timezones.status.builtInCollision": "Durch eingebauten Ort belegt",
            "timezones.status.unknownZone": "Unbekannte Zeitzone",
            "settings.format": "Format",
            "numbers.region": "Zahlenformat",
            "numbers.regionLabel": "Region",
            "numbers.sample": "Beispiel",
            "numbers.syntax": "Funktionsargumente",
            "numbers.convertPaste": "Fremde Zahlen beim Einfügen umwandeln",
            "numbers.convertPasteCap": "Eingefügtes 1,234.56 wird zur lokalen Form, z. B. 1.234,56. Text und lokale Zahlen bleiben unverändert.",
            "numbers.grouping": "Tausendertrennzeichen anzeigen",
            "numbers.groupingCap": "10000 wird als 10.000 (oder lokal) angezeigt",
            "numbers.compact": "Große Zahlen kompakt anzeigen",
            "numbers.compactCap": "100000 wird als 100k angezeigt. Kopierte Werte behalten die volle Präzision.",
            "numbers.confirmTitle": "Zahlenformat ändern?",
            "numbers.confirmBody": "Die Region kann die Zahlen in diesem Blatt neu deuten. Antworten, die sich ändern:",
            "numbers.apply": "Anwenden",
            "numbers.cancel": "Abbrechen",
            // r87: number formatting
            "numbers.format": "Standardformat für Ergebnisse",
            "numbers.formatCap": "So werden Zahlenresultate angezeigt und kopiert. Die Rechengenauigkeit bleibt unverändert.",
            "notation.label": "Zahlendarstellung",
            "negative.label": "Negative Zahlen",
            "negative.minus": "Minus davor (-123)",
            "negative.parentheses": "Klammern (123)",
            "negative.trailingMinus": "Minus dahinter (123-)",
            "currency.label": "Währungssymbol",
            "currency.before": "Davor ($123)",
            "currency.beforeSpaced": "Davor, mit Leerzeichen ($ 123)",
            "currency.after": "Dahinter (123$)",
            "currency.afterSpaced": "Dahinter, mit Leerzeichen (123 $)",
            "negative.cap": "Darstellung negativer Ergebnisse.",
"currency.cap": "Platz des Währungssymbols.",
            "fraction.label": "Bruchnenner",
            "fraction.cap": "Größter Nenner für die Bruchnäherung.",
            "customPattern.label": "Eigenes Format",
            "customPattern.cap": "Ein Zahlengerüst wie #,##0.00: # ist eine Ziffer (Null optional), 0 eine Pflichtziffer. Maximal 96 Zeichen.",
            "customPattern.invalid": "Muster ungültig – Ergebnisse nutzen bis zur Korrektur den Automatikformat.",
            "customPattern.preview": "Vorschau",
            "numberFormat": "Zahlenformat",
            "formatDefault": "Standard",
            "formatAutomatic": "Automatisch",
            "formatDecimal": "Dezimal",
            "formatScientific": "Wissenschaftlich",
            "formatEngineering": "Technisch",
            "formatFraction": "Bruch",
            "formatTimespan": "Zeitspanne",
            "formatCustom": "Eigene",
            "customPatternInvalid": "Gib in den Einstellungen ein gültiges Muster an, um „Eigene“ zu nutzen.",
            "resetFormatting": "Formatierung zurücksetzen",
            "highlight": "Hervorheben",
            "highlightNone": "Keine",
            "highlightYellow": "Gelb",
            "highlightOrange": "Orange",
            "highlightGreen": "Grün",
            "highlightBlue": "Blau",
            "highlightPurple": "Lila",
            "highlightPink": "Pink",
            "styling.column": "Ergebnisspalte",
            "styling.columnCap": "Hintergrund der Ergebnisspalte und Ausrichtung der Ergebnisse.",
            "styling.column.alignment": "Ausrichtung",
            "alignment.leading": "Links",
            "alignment.trailing": "Rechts",
            "styling.column.surface": "Hintergrund",
            "surface.neutral": "Neutral",
            "surface.sand": "Sand",
            "surface.slate": "Schiefer",
            "surface.sage": "Salbei",
            "surface.blush": "Rosa",
            "sheet": "Blatt",
            "empty": "Leer",
            "line": "Zeile",
            "lines": "Zeilen",
            "noLines": "Keine Zeilen",
            "newSheet": "Neues Blatt",
            "deleteSheet": "Blatt löschen",
            "folderGeneral": "Allgemein",
            "newFolder": "Neuer Ordner",
            "renameFolder": "Ordner umbenennen",
            "deleteFolder": "Ordner löschen",
            "deleteFolderHelp": "Die Blätter in diesem Ordner werden nach „Allgemein“ verschoben — es wird kein Blatt gelöscht.",
            "moveToFolder": "In Ordner verschieben",
            "newSheetInFolder": "Neues Blatt im Ordner",
            "dropSheetHere": "Blatt hierher ziehen, um es zu verschieben",
            "folderEmpty": "Keine Blätter",
            "sheets": "Blätter",
            "showSheets": "Blätter anzeigen",
            "hideSheets": "Blätter ausblenden",
            "importSheet": "Blatt importieren (.nlx)",
            "exportSheet": "Blatt exportieren (.nlx)",
            "enter": "Geben Sie einen Ausdruck ein, um zu beginnen",
            "settings": "Einstellungen",
            "total": "Gesamt",
            "copyAnswer": "Antwort kopieren",
            "deleteLine": "Zeile löschen",
            "rounding": "Rundung",
            "roundingDefault": "Standard",
            "editAnswerFormatting": "Antwortformat bearbeiten",
            "decimalPlaces": "Dezimalstellen",
            "weatherUnavailable": "Wetter nicht verfügbar",
            "locationUnavailable": "Standort nicht verfügbar",
            "rename": "Umbenennen",
            "round": "Rundung von Zahlen",
            "fontsize": "Schriftgröße",
            "sheetname": "Titel der Blätter:",
            "language": "Sprache der Schnittstelle:",
            "linenumber": "Zeilennummern:",
            "hideSidebarBtn": "Seitenleisten-Taste nach dem Einklappen ausblenden",
            "hideSidebarBtnCap": "Seitenleiste mit ⌃⌘S (Control-Command-S) einblenden",
            "showTotalBar": "Summenleiste anzeigen",
            "appearance": "Erscheinungsbild:",
            "appearanceLight": "Hell",
            "appearanceDark": "Dunkel",
            "appearanceAuto": "Automatisch",
            "settings.about": "Über",
            "about.documentation": "Dokumentation",
            "about.version": "Version %@",
            "settings.aboutShort": "Über",
            "settings.updates": "Updates",
            "settings.constantsUnits": "Konstanten & Einheiten",
            "settings.constantsUnitsShort": "Konstanten",
            "appIcon": "App-Symbol:",
            "appIconDark": "Dunkel",
            "appIconLight": "Hell",
            "operators": "Operatoren",
            "opPad": "Operatoren mit Leerzeichen umgeben",
            "opPadCap": "1+1 wird 1 + 1",
            "opStar": "* durch × ersetzen",
            "opStarCap": "3*3 wird 3 × 3",
            "opBacktick": "Backtick ` durch + ersetzen",
            "opBacktickCap": "5`5 wird 5 + 5",
            "opQuick": "QuickOperators verwenden",
            "opQuickCap": "5p5 wird 5 + 5, 5m5 wird 5 − 5\n5x5 wird 5 × 5, 5d5 wird 5 ÷ 5",
            "autoInsert": "Automatische Einfügungen",
            "autoGroup": "Tausendertrennzeichen in Zahlen",
            "autoGroupCap": "Gruppiert Zahlen beim Tippen (10000 wird 10,000).",
            "autoPrev": "Vorherige Antwort nach Operator auf neuer Zeile einfügen",
            "autoPrevCap": "Nach Return einen Operator eingeben (+ − × oder ÷)",
            "settings.general": "Allgemein",
            "welcome.getStarted": "Loslegen",
            "welcome.getStartedHint": "Öffnet das Notizbuch",
            "settings.constants": "Konstanten",
            "constants.intro": "In allen Blättern verfügbar. .nlx-Dateien enthalten keine Konstanten.",
            "constants.emptyTitle": "Keine Konstanten",
            "constants.emptyCap": "Konstanten stehen in jedem Blatt zur Verfügung. .nlx-Dateien enthalten keine Konstanten.",
            "units.emptyTitle": "Keine eigenen Einheiten",
            "units.emptyCap": "Eine Definition ist `12 feet` (Vielfaches einer bestehenden Einheit) oder `new unit` (eigene Dimension).",
            "units.tab.constants": "Konstanten",
            "units.tab.units": "Einheiten",
            "units.intro": "In allen Blättern verfügbar. .nlx-Dateien enthalten keine Einheiten. Eine Definition ist `12 feet` (Vielfaches einer bestehenden Einheit) oder `new unit` (eigene Dimension).",
            "units.name": "Name",
            "units.definition": "Definition",
            "units.add": "Einheit hinzufügen",
            "units.delete": "Einheit löschen",
            "units.newUnit": "new unit",
            "units.statusActive": "Aktiv",
            "units.statusEmpty": "Leer",
            "units.statusIncomplete": "Name oder Definition fehlt",
            "units.statusInvalidName": "Ungültiger Name",
            "units.statusDuplicate": "Doppelter Name",
            "units.statusBuiltIn": "Name ist eine eingebaute Einheit",
            "units.statusConstant": "Name ist eine Konstante",
            "units.statusInvalidDefinition": "Ungültige Definition",
            "units.statusUnknown": "Unbekannte Einheit in Definition",
            "units.statusCycle": "Zyklische Definition",
            "units.statusNonFinite": "Definition ist keine positive endliche Zahl",
            "units.statusLimit": "Über dem Limit von 100",
            "constants.name": "Name",
            "constants.value": "Wert",
            "constants.add": "Konstante hinzufügen",
            "constants.delete": "Konstante löschen",
            "constants.incomplete": "Name oder Wert fehlt",
            "constants.invalidName": "Name: 1–6 Wörter, Buchstaben A–Z",
            "constants.duplicate": "Namensduplikat",
            "constants.reserved": "Name ist reserviert",
            "constants.invalidExpression": "Ungültiger Wert",
            "constants.invalidDependency": "Unbekannter Name im Wert",
            "constants.cycle": "Zirkulärer Bezug",
            "constants.exceedsLimit": "Zeilenlimit erreicht",
            "settings.styling": "Stil",
            "settings.stylingShort": "Stil",
            "settings.editing": "Bearbeiten",
            "general.interface": "Oberfläche",
            "general.notebook": "Notizbuch",
            "numbers.answer": "Antwortanzeige",
            "numbers.pasting": "Einfügen",
            "styling.typography": "Typografie",
            "styling.colors": "Syntaxfarben",
            "styling.colorsCap": "Preset- oder benutzerdefinierte Farben für jede Rolle. Die Standard-Aktion stellt den Werks-Preset der Rolle wieder her.",
            "styling.colors.custom": "Benutzerdefiniert",
            "styling.colors.default": "Standard",
            "styling.colors.resetRole": "Standardfarbe für diese Rolle wiederherstellen",
            "styling.colors.resetAll": "Farben zurücksetzen",
            "styling.colors.resetAllCap": "Stellt die Standard-Syntaxfarben wieder her. Schrift- und Antwortspalteneinstellungen bleiben erhalten.",
            "styling.colors.pick": "Benutzerdefinierte Farbe für diese Rolle wählen",
            "roundingCap": "Ergebnisse werden auf diese Nachkommastellen gerundet.",
            "styling.fontsize": "Schriftgröße:",
            "styling.font": "Schriftart:",
            "styling.font.system": "Systemschrift",
            "styling.font.rounded": "Rund",
            "styling.font.serif": "Serife",
            "styling.font.monospaced": "Monospaziert",
            "styling.color.standardText": "Standardtext",
            "styling.color.cyan": "Cyan",
            "styling.color.green": "Grün",
            "styling.color.pinkPurple": "Rosalila",
            "styling.color.blue": "Blau",
            "styling.color.moneyPurple": "Violett",
            "styling.role.numbers": "Zahlen",
            "styling.role.operators": "Operatoren",
            "styling.role.variables": "Variablen",
            "styling.role.units": "Einheiten",
            "styling.role.specifiers": "Bindewörter",
            "styling.role.headings": "Überschriften",
            "styling.role.comments": "Kommentare",
            "styling.role.labels": "Beschriftungen",
            "styling.preview": "Vorschau",
            "updates.group": "Updates",
            "updates.checkNow": "Nach Updates suchen…",
            "updates.checkNowShort": "Jetzt prüfen",
            "updates.auto": "Automatisch nach Updates suchen",
            "updates.autoCap": "Numlex sucht im Hintergrund nach einer neuen Version und fragt vor der Installation nach.",
            "updates.unavailable": "In diesem Build sind Updates nicht verfügbar.",
            "updates.unavailable.notPackaged": "Dieser Entwicklungs-Build ist kein App-Bundle; Updates sind daher deaktiviert.",
            "updates.unavailable.missingFeedURL": "In diesem Build ist kein Update-Feed konfiguriert; Updates sind daher deaktiviert.",
            "updates.unavailable.insecureFeedURL": "Die Update-Feed-URL ist keine sichere HTTPS-Adresse; Updates sind daher deaktiviert.",
            "updates.unavailable.missingPublicKey": "In diesem Build fehlt der Update-Prüfschlüssel; Updates sind daher deaktiviert.",
            "updates.unavailable.invalidPublicKey": "Der Update-Prüfschlüssel in diesem Build ist ungültig; Updates sind daher deaktiviert.",
        ],
        .fr: [
            "settings.numbers": "Nombres",
            "settings.datesTimes": "Dates et heures",
            "settings.datesTimesShort": "Dates",
            "datesTimes.work": "Calendrier de travail",
            "holidayRegion.label": "Région des jours fériés",
            "holidayRegion.automatic": "Automatique (région du système)",
            "holidayRegion.cap": "Les jours ouvrés excluent les jours fériés de la région choisie. Les régions non prises en charge provoquent une erreur dans les requêtes datées.",
            "hoursPerWorkday.label": "Heures par jour ouvré",
            "hoursPerWorkday.cap": "Utilisé pour les heures de travail et la conversion des jours ouvrés. Entre 1 et 24.",
            "timezones.group": "Fuseaux horaires personnalisés",
            "timezones.intro": "Nommez un fuseau horaire que vous utilisez souvent et demandez-le par son nom — par exemple, time in Bureau. Seules les lignes actives sont disponibles dans les feuilles.",
            "timezones.add": "Ajouter un fuseau",
            "timezones.name": "Nom",
            "timezones.identifier": "Identifiant IANA",
            "timezones.delete": "Supprimer le fuseau",
            "timezones.emptyTitle": "Aucun fuseau personnalisé",
            "timezones.emptyCap": "Ajoutez un alias pour un fuseau que vous utilisez souvent, puis demandez-le par son nom dans n'importe quelle feuille.",
            "timezones.status.active": "Actif",
            "timezones.status.incomplete": "Saisissez un nom et un identifiant",
            "timezones.status.invalidName": "Nom non valide",
            "timezones.status.duplicate": "Nom en double",
            "timezones.status.builtInCollision": "Réservé par un lieu intégré",
            "timezones.status.unknownZone": "Fuseau inconnu",
            "settings.format": "Format",
            "numbers.region": "Format des nombres",
            "numbers.regionLabel": "Région",
            "numbers.sample": "Exemple",
            "numbers.syntax": "Arguments de fonction",
            "numbers.convertPaste": "Convertir les nombres étrangers lors du collage",
            "numbers.convertPasteCap": "Un collage de 1,234.56 devient la forme locale, p. ex. 1 234,56. Le texte et les nombres locaux sont inchangés.",
            "numbers.grouping": "Afficher le séparateur de milliers",
            "numbers.groupingCap": "10000 s'affiche comme 10 000 (ou forme locale)",
            "numbers.compact": "Nombres grands en forme compacte",
            "numbers.compactCap": "100000 s'affiche comme 100k. Les valeurs copiées gardent la précision complète.",
            "numbers.confirmTitle": "Changer le format des nombres ?",
            "numbers.confirmBody": "Changer de région peut réinterpréter les nombres de cette feuille. Réponses modifiées :",
            "numbers.apply": "Appliquer",
            "numbers.cancel": "Annuler",
            // r87: number formatting
            "numbers.format": "Format de résultat par défaut",
            "numbers.formatCap": "Comment les résultats numériques sont affichés et copiés. La précision de calcul ne change jamais.",
            "notation.label": "Notation",
            "negative.label": "Nombres négatifs",
            "negative.minus": "Moins préfixe (-123)",
            "negative.parentheses": "Parenthèses (123)",
            "negative.trailingMinus": "Moins suffixe (123-)",
            "currency.label": "Symbole monétaire",
            "currency.before": "Avant ($123)",
            "currency.beforeSpaced": "Avant, espacé ($ 123)",
            "currency.after": "Après (123$)",
            "currency.afterSpaced": "Après, espacé (123 $)",
            "negative.cap": "Affichage des résultats négatifs.",
"currency.cap": "Position du symbole monétaire.",
            "fraction.label": "Dénominateur de fraction",
            "fraction.cap": "Dénominateur maximal de l'approximation fractionnaire.",
            "customPattern.label": "Format personnalisé",
            "customPattern.cap": "Un squelette numérique comme #,##0.00 : # est un chiffre (zéro optionnel), 0 un chiffre obligatoire. 96 caractères maximum.",
            "customPattern.invalid": "Motif invalide — les résultats utilisent le format automatique jusqu'à correction.",
            "customPattern.preview": "Aperçu",
            "numberFormat": "Format numérique",
            "formatDefault": "Par défaut",
            "formatAutomatic": "Automatique",
            "formatDecimal": "Décimal",
            "formatScientific": "Scientifique",
            "formatEngineering": "Ingénierie",
            "formatFraction": "Fraction",
            "formatTimespan": "Durée",
            "formatCustom": "Personnalisé",
            "customPatternInvalid": "Définis un motif valide dans les Réglages pour utiliser Personnalisé.",
            "resetFormatting": "Réinitialiser la mise en forme",
            "highlight": "Surligner",
            "highlightNone": "Aucun",
            "highlightYellow": "Jaune",
            "highlightOrange": "Orange",
            "highlightGreen": "Vert",
            "highlightBlue": "Bleu",
            "highlightPurple": "Violet",
            "highlightPink": "Rose",
            "styling.column": "Colonne de résultats",
            "styling.columnCap": "Fond de la colonne et position des résultats dans la colonne.",
            "styling.column.alignment": "Alignement",
            "alignment.leading": "Gauche",
            "alignment.trailing": "Droite",
            "styling.column.surface": "Fond",
            "surface.neutral": "Neutre",
            "surface.sand": "Sable",
            "surface.slate": "Ardoise",
            "surface.sage": "Sauge",
            "surface.blush": "Rose",
            "sheet": "Feuille",
            "empty": "Vide",
            "line": "ligne",
            "lines": "lignes",
            "noLines": "Aucune ligne",
            "newSheet": "Nouvelle feuille",
            "deleteSheet": "Supprimer la feuille",
            "folderGeneral": "Général",
            "newFolder": "Nouvel dossier",
            "renameFolder": "Renommer le dossier",
            "deleteFolder": "Supprimer le dossier",
            "deleteFolderHelp": "Les feuilles de ce dossier sont déplacées vers « Général » — aucune feuille n'est supprimée.",
            "moveToFolder": "Déplacer vers le dossier",
            "newSheetInFolder": "Nouvelle feuille dans le dossier",
            "dropSheetHere": "Déposez une feuille ici pour la déplacer",
            "folderEmpty": "Aucune feuille",
            "sheets": "Feuilles",
            "showSheets": "Afficher les feuilles",
            "hideSheets": "Masquer les feuilles",
            "importSheet": "Importer (.nlx)",
            "exportSheet": "Exporter (.nlx)",
            "enter": "Saisissez une expression",
            "settings": "Réglages",
            "total": "Total",
            "copyAnswer": "Copier la réponse",
            "deleteLine": "Supprimer la ligne",
            "rounding": "Arrondi",
            "roundingDefault": "Par défaut",
            "editAnswerFormatting": "Modifier le format de la réponse",
            "decimalPlaces": "décimales",
            "weatherUnavailable": "Météo indisponible",
            "locationUnavailable": "Emplacement indisponible",
            "rename": "Renommer",
            "round": "Arrondi:",
            "fontsize": "Taille de police:",
            "sheetname": "Titre:",
            "language": "Langue:",
            "linenumber": "Numéros de ligne:",
            "hideSidebarBtn": "Masquer le bouton de la barre latérale une fois réduite",
            "hideSidebarBtnCap": "Réafficher la barre latérale avec ⌃⌘S (Contrôle-Commande-S)",
            "showTotalBar": "Afficher la barre de total",
            "appearance": "Apparence:",
            "appearanceLight": "Clair",
            "appearanceDark": "Sombre",
            "appearanceAuto": "Automatique",
            "settings.about": "À propos",
            "about.documentation": "Documentation",
            "about.version": "Version %@",
            "settings.aboutShort": "À propos",
            "settings.updates": "Mises à jour",
            "settings.constantsUnits": "Constantes et unités",
            "settings.constantsUnitsShort": "Constantes",
            "appIcon": "Icône de l’application :",
            "appIconDark": "Sombre",
            "appIconLight": "Claire",
            "operators": "Opérateurs",
            "opPad": "Espacer les opérateurs",
            "opPadCap": "1+1 devient 1 + 1",
            "opStar": "Remplacer * par ×",
            "opStarCap": "3*3 devient 3 × 3",
            "opBacktick": "Remplacer la backtick ` par +",
            "opBacktickCap": "5`5 devient 5 + 5",
            "opQuick": "Utiliser QuickOperators",
            "opQuickCap": "5p5 devient 5 + 5, 5m5 devient 5 − 5\n5x5 devient 5 × 5, 5d5 devient 5 ÷ 5",
            "autoInsert": "Insertions automatiques",
            "autoGroup": "Séparateurs de milliers",
            "autoGroupCap": "Groupe les nombres saisis pendant la saisie (10000 devient 10 000).",
            "autoPrev": "Insérer la réponse précédente après un opérateur sur une nouvelle ligne",
            "autoPrevCap": "Après Retour, tapez un opérateur (+ − × ou ÷)",
            "settings.general": "Général",
            "welcome.getStarted": "Commencer",
            "welcome.getStartedHint": "Ouvre le bloc-notes",
            "settings.constants": "Constantes",
            "constants.intro": "Disponibles dans toutes les feuilles. Les exports .nlx ne les incluent pas.",
            "constants.emptyTitle": "Aucune constante",
            "constants.emptyCap": "Les constantes sont disponibles dans toutes les feuilles. Les exports .nlx ne les incluent pas.",
            "units.emptyTitle": "Aucune unité personnalisée",
            "units.emptyCap": "Une définition est `12 feet` (multiple d’une unité existante) ou `new unit` (dimension indépendante).",
            "units.tab.constants": "Constantes",
            "units.tab.units": "Unités",
            "units.intro": "Disponibles dans toutes les feuilles. Les exports .nlx n'incluent pas les unités. Une définition est `12 feet` (multiple d'une unité existante) ou `new unit` (dimension indépendante).",
            "units.name": "Nom",
            "units.definition": "Définition",
            "units.add": "Ajouter une unité",
            "units.delete": "Supprimer l'unité",
            "units.newUnit": "new unit",
            "units.statusActive": "Active",
            "units.statusEmpty": "Vide",
            "units.statusIncomplete": "Nom ou définition manquante",
            "units.statusInvalidName": "Nom invalide",
            "units.statusDuplicate": "Nom en double",
            "units.statusBuiltIn": "Nom déjà utilisé par une unité intégrée",
            "units.statusConstant": "Nom d'une constante",
            "units.statusInvalidDefinition": "Définition invalide",
            "units.statusUnknown": "Unité inconnue dans la définition",
            "units.statusCycle": "Définition circulaire",
            "units.statusNonFinite": "Définition non numérique positive finie",
            "units.statusLimit": "Au-delà de la limite de 100",
            "constants.name": "Nom",
            "constants.value": "Valeur",
            "constants.add": "Ajouter une constante",
            "constants.delete": "Supprimer la constante",
            "constants.incomplete": "Nom ou valeur manquant",
            "constants.invalidName": "Nom : 1 à 6 mots, lettres A–Z",
            "constants.duplicate": "Nom en double",
            "constants.reserved": "Nom réservé",
            "constants.invalidExpression": "Valeur invalide",
            "constants.invalidDependency": "Nom inconnu dans la valeur",
            "constants.cycle": "Référence circulaire",
            "constants.exceedsLimit": "Limite de lignes atteinte",
            "settings.styling": "Style",
            "settings.stylingShort": "Style",
            "settings.editing": "Édition",
            "general.interface": "Interface",
            "general.notebook": "Cahier",
            "numbers.answer": "Affichage des réponses",
            "numbers.pasting": "Collage",
            "styling.typography": "Typographie",
            "styling.colors": "Couleurs de syntaxe",
            "styling.colorsCap": "Couleurs prédéfinies ou personnalisées pour chaque rôle. L'action Par défaut rétablit le preset d'usine du rôle.",
            "styling.colors.custom": "Personnalisé",
            "styling.colors.default": "Par défaut",
            "styling.colors.resetRole": "Rétablir la couleur par défaut de ce rôle",
            "styling.colors.resetAll": "Réinitialiser les couleurs de syntaxe",
            "styling.colors.resetAllCap": "Restaure les couleurs de syntaxe par défaut. Les réglages de police et de colonne des réponses sont conservés.",
            "styling.colors.pick": "Choisir une couleur personnalisée pour ce rôle",
            "roundingCap": "Les résultats sont arrondis à ce nombre de décimales.",
            "styling.fontsize": "Taille de police:",
            "styling.font": "Police:",
            "styling.font.system": "Police système",
            "styling.font.rounded": "Arrondi",
            "styling.font.serif": "Serif",
            "styling.font.monospaced": "Monospace",
            "styling.color.standardText": "Texte standard",
            "styling.color.cyan": "Cyan",
            "styling.color.green": "Vert",
            "styling.color.pinkPurple": "Rose-violet",
            "styling.color.blue": "Bleu",
            "styling.color.moneyPurple": "Violet",
            "styling.role.numbers": "Nombres",
            "styling.role.operators": "Opérateurs",
            "styling.role.variables": "Variables",
            "styling.role.units": "Unités",
            "styling.role.specifiers": "Mots de liaison",
            "styling.role.headings": "Titres",
            "styling.role.comments": "Commentaires",
            "styling.role.labels": "Libellés",
            "styling.preview": "Aperçu",
            "updates.group": "Mises à jour",
            "updates.checkNow": "Rechercher les mises à jour…",
            "updates.checkNowShort": "Vérifier",
            "updates.auto": "Rechercher automatiquement les mises à jour",
            "updates.autoCap": "Numlex recherche une nouvelle version en arrière-plan et demande avant de l'installer.",
            "updates.unavailable": "Les mises à jour ne sont pas disponibles dans cette version.",
            "updates.unavailable.notPackaged": "Cette version de développement n'est pas une application empaquetée ; les mises à jour sont désactivées.",
            "updates.unavailable.missingFeedURL": "Aucun flux de mise à jour n'est configuré dans cette version ; les mises à jour sont désactivées.",
            "updates.unavailable.insecureFeedURL": "L'URL du flux de mise à jour n'est pas une adresse HTTPS sécurisée ; les mises à jour sont désactivées.",
            "updates.unavailable.missingPublicKey": "Cette version n'a pas de clé de vérification des mises à jour ; les mises à jour sont désactivées.",
            "updates.unavailable.invalidPublicKey": "La clé de vérification des mises à jour de cette version est invalide ; les mises à jour sont désactivées.",
        ],
        .it: [
            "settings.numbers": "Numeri",
            "settings.datesTimes": "Date e ore",
            "settings.datesTimesShort": "Date",
            "datesTimes.work": "Calendario lavorativo",
            "holidayRegion.label": "Regione festiva",
            "holidayRegion.automatic": "Automatico (regione di sistema)",
            "holidayRegion.cap": "I giorni lavorativi escludono le festività della regione scelta. Le regioni non supportate danno errore nelle query con date.",
            "hoursPerWorkday.label": "Ore per giorno lavorativo",
            "hoursPerWorkday.cap": "Usato per le ore di lavoro e la conversione dei giorni lavorativi. Tra 1 e 24.",
            "timezones.group": "Fusi orari personalizzati",
            "timezones.intro": "Dai un nome a un fuso orario che usi spesso e chiedilo per nome — ad esempio, time in Ufficio. Solo le righe attive sono disponibili nei fogli.",
            "timezones.add": "Aggiungi fuso",
            "timezones.name": "Nome",
            "timezones.identifier": "Identificatore IANA",
            "timezones.delete": "Elimina fuso",
            "timezones.emptyTitle": "Nessun fuso personalizzato",
            "timezones.emptyCap": "Aggiungi un alias per un fuso che usi spesso, poi chiedilo per nome in qualsiasi foglio.",
            "timezones.status.active": "Attivo",
            "timezones.status.incomplete": "Inserisci nome e identificatore",
            "timezones.status.invalidName": "Nome non valido",
            "timezones.status.duplicate": "Nome duplicato",
            "timezones.status.builtInCollision": "Riservato da un luogo integrato",
            "timezones.status.unknownZone": "Fuso sconosciuto",
            "settings.format": "Format",
            "numbers.region": "Formato numerico",
            "numbers.regionLabel": "Regione",
            "numbers.sample": "Esempio",
            "numbers.syntax": "Argomenti delle funzioni",
            "numbers.convertPaste": "Converti i numeri stranieri all'incollaggio",
            "numbers.convertPasteCap": "Un incolla di 1,234.56 diventa la forma locale, es. 1.234,56. Il testo e i numeri locali restano invariati.",
            "numbers.grouping": "Mostra il separatore delle migliaia",
            "numbers.groupingCap": "10000 viene visualizzato come 10.000 (o forma locale)",
            "numbers.compact": "Numeri grandi in forma compatta",
            "numbers.compactCap": "100000 viene visualizzato come 100k. I valori copiati mantengono la precisione completa.",
            "numbers.confirmTitle": "Cambiare il formato numerico?",
            "numbers.confirmBody": "La regione può ridefinire i numeri in questo foglio. Risultati che cambiano:",
            "numbers.apply": "Applica",
            "numbers.cancel": "Annulla",
            // r87: number formatting
            "numbers.format": "Formato risposta predefinito",
            "numbers.formatCap": "Come i risultati numerici vengono visualizzati e copiati. La precisione di calcolo non cambia mai.",
            "notation.label": "Notazione",
            "negative.label": "Numeri negativi",
            "negative.minus": "Meno prefisso (-123)",
            "negative.parentheses": "Parentesi (123)",
            "negative.trailingMinus": "Meno suffisso (123-)",
            "currency.label": "Simbolo valuta",
            "currency.before": "Prima ($123)",
            "currency.beforeSpaced": "Prima, spaziato ($ 123)",
            "currency.after": "Dopo (123$)",
            "currency.afterSpaced": "Dopo, spaziato (123 $)",
            "negative.cap": "Visualizzazione dei risultati negativi.",
"currency.cap": "Posizione del simbolo di valuta.",
            "fraction.label": "Denominatore frazione",
            "fraction.cap": "Denominatore massimo dell'approssimazione frazionaria.",
            "customPattern.label": "Formato personalizzato",
            "customPattern.cap": "Uno scheletro numerico come #,##0.00: # è una cifra (zero opzionale), 0 una cifra obbligatoria. 96 caratteri max.",
            "customPattern.invalid": "Modello non valido: i risultati usano il formato automatico finché non viene corretto.",
            "customPattern.preview": "Anteprima",
            "numberFormat": "Formato numerico",
            "formatDefault": "Predefinito",
            "formatAutomatic": "Automatico",
            "formatDecimal": "Decimale",
            "formatScientific": "Scientifico",
            "formatEngineering": "Ingegneristico",
            "formatFraction": "Frazione",
            "formatTimespan": "Intervallo",
            "formatCustom": "Personalizzato",
            "customPatternInvalid": "Imposta un modello valido nelle Impostazioni per usare Personalizzato.",
            "resetFormatting": "Ripristina formattazione",
            "highlight": "Evidenzia",
            "highlightNone": "Nessun",
            "highlightYellow": "Giallo",
            "highlightOrange": "Arancione",
            "highlightGreen": "Verde",
            "highlightBlue": "Blu",
            "highlightPurple": "Viola",
            "highlightPink": "Rosa",
            "styling.column": "Colonna risultati",
            "styling.columnCap": "Fondo della colonna e posizione dei risultati in essa.",
            "styling.column.alignment": "Allineamento",
            "alignment.leading": "Sinistro",
            "alignment.trailing": "Destro",
            "styling.column.surface": "Sfondo",
            "surface.neutral": "Neutro",
            "surface.sand": "Sabbia",
            "surface.slate": "Ardesia",
            "surface.sage": "Salvia",
            "surface.blush": "Rosa",
            "sheet": "Foglio",
            "empty": "Vuoto",
            "line": "riga",
            "lines": "righe",
            "noLines": "Nessuna riga",
            "newSheet": "Nuovo foglio",
            "deleteSheet": "Elimina foglio",
            "folderGeneral": "Generale",
            "newFolder": "Nuova cartella",
            "renameFolder": "Rinomina cartella",
            "deleteFolder": "Elimina cartella",
            "deleteFolderHelp": "I fogli in questa cartella vengono spostati in „Generale“ — nessun foglio viene eliminato.",
            "moveToFolder": "Sposta nella cartella",
            "newSheetInFolder": "Nuovo foglio nella cartella",
            "dropSheetHere": "Rilascia un foglio qui per spostarlo",
            "folderEmpty": "Nessun foglio",
            "sheets": "Fogli",
            "showSheets": "Mostra fogli",
            "hideSheets": "Nascondi fogli",
            "importSheet": "Importa (.nlx)",
            "exportSheet": "Esporta (.nlx)",
            "enter": "Inserisci un'espressione",
            "settings": "Impostazioni",
            "total": "Totale",
            "copyAnswer": "Copia risposta",
            "deleteLine": "Elimina riga",
            "rounding": "Arrotondamento",
            "roundingDefault": "Predefinito",
            "editAnswerFormatting": "Modifica il formato della risposta",
            "decimalPlaces": "case decimali",
            "weatherUnavailable": "Meteo non disponibile",
            "locationUnavailable": "Posizione non disponibile",
            "rename": "Rinomina",
            "round": "Arrotondamento:",
            "fontsize": "Dimensione:",
            "sheetname": "Titolo:",
            "language": "Lingua:",
            "linenumber": "Numeri di riga:",
            "hideSidebarBtn": "Nascondi il pulsante della barra laterale dopo la compressione",
            "hideSidebarBtnCap": "Mostra di nuovo la barra laterale con ⌃⌘S (Control-Comando-S)",
            "showTotalBar": "Mostra barra del totale",
            "appearance": "Aspetto:",
            "appearanceLight": "Chiaro",
            "appearanceDark": "Scuro",
            "appearanceAuto": "Automatico",
            "settings.about": "Informazioni",
            "about.documentation": "Documentazione",
            "about.version": "Versione %@",
            "settings.aboutShort": "Info",
            "settings.updates": "Aggiornamenti",
            "settings.constantsUnits": "Costanti e unità",
            "settings.constantsUnitsShort": "Costanti",
            "appIcon": "Icona dell’app:",
            "appIconDark": "Scuro",
            "appIconLight": "Chiaro",
            "operators": "Operatori",
            "opPad": "Spaziatura intorno agli operatori",
            "opPadCap": "1+1 diventa 1 + 1",
            "opStar": "Sostituisci * con ×",
            "opStarCap": "3*3 diventa 3 × 3",
            "opBacktick": "Sostituisci backtick ` con +",
            "opBacktickCap": "5`5 diventa 5 + 5",
            "opQuick": "Usa QuickOperators",
            "opQuickCap": "5p5 diventa 5 + 5, 5m5 diventa 5 − 5\n5x5 diventa 5 × 5, 5d5 diventa 5 ÷ 5",
            "autoInsert": "Inserimenti automatici",
            "autoGroup": "Separatore delle migliaia",
            "autoGroupCap": "Raggruppa i numeri mentre digiti (10000 diventa 10.000).",
            "autoPrev": "Inserisci la risposta precedente dopo un operatore su una nuova riga",
            "autoPrevCap": "Dopo Invio, digita un operatore (+ − × o ÷)",
            "settings.general": "Generali",
            "welcome.getStarted": "Inizia",
            "welcome.getStartedHint": "Apre il blocco note",
            "settings.constants": "Costanti",
            "constants.intro": "Disponibili in ogni foglio. Gli esport .nlx non includono le costanti.",
            "constants.emptyTitle": "Nessuna costante",
            "constants.emptyCap": "Le costanti sono disponibili in ogni foglio. Gli esport .nlx non le includono.",
            "units.emptyTitle": "Nessuna unità personalizzata",
            "units.emptyCap": "Una definizione è `12 feet` (multiplo di un’unità esistente) o `new unit` (dimensione indipendente).",
            "units.tab.constants": "Costanti",
            "units.tab.units": "Unità",
            "units.intro": "Disponibili in ogni foglio. Gli esport .nlx non includono le unità. Una definizione è `12 feet` (multiplo di un'unità esistente) o `new unit` (dimensione indipendente).",
            "units.name": "Nome",
            "units.definition": "Definizione",
            "units.add": "Aggiungi unità",
            "units.delete": "Elimina unità",
            "units.newUnit": "new unit",
            "units.statusActive": "Attiva",
            "units.statusEmpty": "Vuota",
            "units.statusIncomplete": "Nome o definizione mancanti",
            "units.statusInvalidName": "Nome non valido",
            "units.statusDuplicate": "Nome duplicato",
            "units.statusBuiltIn": "Il nome è un'unità integrata",
            "units.statusConstant": "Il nome è una costante",
            "units.statusInvalidDefinition": "Definizione non valida",
            "units.statusUnknown": "Unità sconosciuta nella definizione",
            "units.statusCycle": "Definizione circolare",
            "units.statusNonFinite": "La definizione non è un numero positivo finito",
            "units.statusLimit": "Oltre il limite di 100",
            "constants.name": "Nome",
            "constants.value": "Valore",
            "constants.add": "Aggiungi costante",
            "constants.delete": "Elimina costante",
            "constants.incomplete": "Manca nome o valore",
            "constants.invalidName": "Nome: 1–6 parole, lettere A–Z",
            "constants.duplicate": "Nome duplicato",
            "constants.reserved": "Nome riservato",
            "constants.invalidExpression": "Valore non valido",
            "constants.invalidDependency": "Nome sconosciuto nel valore",
            "constants.cycle": "Riferimento circolare",
            "constants.exceedsLimit": "Limite di righe raggiunto",
            "settings.styling": "Stile",
            "settings.stylingShort": "Stile",
            "settings.editing": "Modifica",
            "general.interface": "Interfaccia",
            "general.notebook": "Quaderno",
            "numbers.answer": "Visualizzazione risposte",
            "numbers.pasting": "Incolla",
            "styling.typography": "Tipografia",
            "styling.colors": "Colori sintassi",
            "styling.colorsCap": "Colori predefiniti o personalizzati per ogni ruolo. L'azione Predefinito ripristina il preset di fabbrica del ruolo.",
            "styling.colors.custom": "Personalizzato",
            "styling.colors.default": "Predefinito",
            "styling.colors.resetRole": "Ripristina il colore predefinito per questo ruolo",
            "styling.colors.resetAll": "Reimposta colori di sintassi",
            "styling.colors.resetAllCap": "Ripristina i colori di sintassi predefiniti. Le impostazioni di font e della colonna dei risultati restano invariate.",
            "styling.colors.pick": "Scegli un colore personalizzato per questo ruolo",
            "roundingCap": "I risultati vengono arrotondati a questo numero di cifre decimali.",
            "styling.fontsize": "Dimensione carattere:",
            "styling.font": "Carattere:",
            "styling.font.system": "Carattere di sistema",
            "styling.font.rounded": "Arrotondato",
            "styling.font.serif": "Serif",
            "styling.font.monospaced": "Monospazio",
            "styling.color.standardText": "Testo standard",
            "styling.color.cyan": "Ciano",
            "styling.color.green": "Verde",
            "styling.color.pinkPurple": "Rosa-viola",
            "styling.color.blue": "Blu",
            "styling.color.moneyPurple": "Viola",
            "styling.role.numbers": "Numeri",
            "styling.role.operators": "Operatori",
            "styling.role.variables": "Variabili",
            "styling.role.units": "Unità",
            "styling.role.specifiers": "Connettivi",
            "styling.role.headings": "Titoli",
            "styling.role.comments": "Commenti",
            "styling.role.labels": "Etichette",
            "styling.preview": "Anteprima",
            "updates.group": "Aggiornamenti",
            "updates.checkNow": "Verifica aggiornamenti…",
            "updates.checkNowShort": "Verifica",
            "updates.auto": "Verifica automaticamente gli aggiornamenti",
            "updates.autoCap": "Numlex controlla in background se esiste una nuova versione e chiede prima di installarla.",
            "updates.unavailable": "In questa build gli aggiornamenti non sono disponibili.",
            "updates.unavailable.notPackaged": "Questa build di sviluppo non è un'app in pacchetto; gli aggiornamenti sono disattivati.",
            "updates.unavailable.missingFeedURL": "In questa build non è configurato alcun feed di aggiornamento; gli aggiornamenti sono disattivati.",
            "updates.unavailable.insecureFeedURL": "L'URL del feed di aggiornamento non è un indirizzo HTTPS sicuro; gli aggiornamenti sono disattivati.",
            "updates.unavailable.missingPublicKey": "In questa build manca la chiave di verifica degli aggiornamenti; gli aggiornamenti sono disattivati.",
            "updates.unavailable.invalidPublicKey": "La chiave di verifica degli aggiornamenti di questa build non è valida; gli aggiornamenti sono disattivati.",
        ],
        .zh: [
            "settings.numbers": "数字",
            "settings.datesTimes": "日期与时间",
            "settings.datesTimesShort": "日期",
            "datesTimes.work": "工作日历",
            "holidayRegion.label": "节假日地区",
            "holidayRegion.automatic": "自动（系统地区）",
            "holidayRegion.cap": "工作日会排除所选地区的公共假日。不支持的地区会在带日期的查询中报错。",
            "hoursPerWorkday.label": "每个工作日的小时数",
            "hoursPerWorkday.cap": "用于工时和工作日换算。取值 1 到 24。",
            "timezones.group": "自定义时区",
            "timezones.intro": "为你常用的时区命名，然后按名称查询——例如 time in 办公室。只有状态为可用的行才会在表格中生效。",
            "timezones.add": "添加时区",
            "timezones.name": "名称",
            "timezones.identifier": "IANA 标识符",
            "timezones.delete": "删除时区",
            "timezones.emptyTitle": "暂无自定义时区",
            "timezones.emptyCap": "为常用时区添加别名，然后在任意表格中按名称查询。",
            "timezones.status.active": "可用",
            "timezones.status.incomplete": "请输入名称和标识符",
            "timezones.status.invalidName": "名称无效",
            "timezones.status.duplicate": "名称重复",
            "timezones.status.builtInCollision": "与内置地点冲突",
            "timezones.status.unknownZone": "未知时区",
            "settings.format": "格式",
            "numbers.region": "数字格式",
            "numbers.regionLabel": "地区",
            "numbers.sample": "示例",
            "numbers.syntax": "函数参数",
            "numbers.convertPaste": "粘贴时转换外来数字",
            "numbers.convertPasteCap": "粘贴的 1,234.56 会变为本地形式，例如 1.234,56。文本和本地数字保持不变。",
            "numbers.grouping": "显示千位分隔符",
            "numbers.groupingCap": "10000 显示为 10,000（或本地形式）",
            "numbers.compact": "紧凑显示大数字",
            "numbers.compactCap": "100000 显示为 100k。复制的值保留完整精度。",
            "numbers.confirmTitle": "更改数字格式？",
            "numbers.confirmBody": "更改地区可能重新解释本表中的数字。发生变化的结果：",
            "numbers.apply": "应用",
            "numbers.cancel": "取消",
            // r87: number formatting
            "numbers.format": "默认结果格式",
            "numbers.formatCap": "数值的显示与复制方式。计算精度从不改变。",
            "notation.label": "记法",
            "negative.label": "负数",
            "negative.minus": "前缀负号 (-123)",
            "negative.parentheses": "括号 (123)",
            "negative.trailingMinus": "后缀负号 (123-)",
            "currency.label": "货币符号",
            "currency.before": "前缀 ($123)",
            "currency.beforeSpaced": "前缀带空格 ($ 123)",
            "currency.after": "后缀 (123$)",
            "currency.afterSpaced": "后缀带空格 (123 $)",
            "negative.cap": "负数结果的显示方式。",
"currency.cap": "货币符号的位置。",
            "fraction.label": "分数分母",
            "fraction.cap": "分数近似允许的最大分母。",
            "customPattern.label": "自定义格式",
            "customPattern.cap": "数字骨架，如 #,##0.00：# 是数字（零可选），0 是必需数字。最多 96 个字符。",
            "customPattern.invalid": "模式无效——修正前结果使用自动格式。",
            "customPattern.preview": "预览",
            "numberFormat": "数字格式",
            "formatDefault": "默认",
            "formatAutomatic": "自动",
            "formatDecimal": "十进制",
            "formatScientific": "科学计数法",
            "formatEngineering": "工程计数法",
            "formatFraction": "分数",
            "formatTimespan": "时间跨度",
            "formatCustom": "自定义",
            "customPatternInvalid": "请在设置中填写有效的自定义模式以使用自定义格式。",
            "resetFormatting": "恢复默认格式",
            "highlight": "高亮",
            "highlightNone": "无",
            "highlightYellow": "黄色",
            "highlightOrange": "橙色",
            "highlightGreen": "绿色",
            "highlightBlue": "蓝色",
            "highlightPurple": "紫色",
            "highlightPink": "粉色",
            "styling.column": "结果列",
            "styling.columnCap": "结果列的背景与结果在列中的位置。",
            "styling.column.alignment": "对齐",
            "alignment.leading": "左对齐",
            "alignment.trailing": "右对齐",
            "styling.column.surface": "背景",
            "surface.neutral": "中性",
            "surface.sand": "沙色",
            "surface.slate": "石板",
            "surface.sage": "鼠尾草",
            "surface.blush": "腮红",
            "sheet": "工作表",
            "empty": "空",
            "line": "行",
            "lines": "行",
            "noLines": "无行",
            "newSheet": "新建工作表",
            "deleteSheet": "删除工作表",
            "folderGeneral": "常规",
            "newFolder": "新建文件夹",
            "renameFolder": "重命名文件夹",
            "deleteFolder": "删除文件夹",
            "deleteFolderHelp": "该文件夹中的工作表会移到“常规”，不会删除任何工作表。",
            "moveToFolder": "移动到文件夹",
            "newSheetInFolder": "在文件夹中新建工作表",
            "dropSheetHere": "将工作表拖放到此处以移动",
            "folderEmpty": "没有工作表",
            "sheets": "工作表",
            "showSheets": "显示工作表",
            "hideSheets": "隐藏工作表",
            "importSheet": "导入 (.nlx)",
            "exportSheet": "导出 (.nlx)",
            "enter": "输入表达式开始",
            "settings": "设置",
            "total": "总计",
            "copyAnswer": "复制答案",
            "deleteLine": "删除行",
            "rounding": "舍入",
            "roundingDefault": "默认",
            "editAnswerFormatting": "编辑答案格式",
            "decimalPlaces": "小数位",
            "weatherUnavailable": "天气不可用",
            "locationUnavailable": "位置不可用",
            "rename": "重命名",
            "round": "小数位:",
            "fontsize": "字号:",
            "sheetname": "标题:",
            "language": "语言:",
            "linenumber": "行号:",
            "hideSidebarBtn": "收起后隐藏边栏按钮",
            "hideSidebarBtnCap": "使用 ⌃⌘S (Control-Command-S) 显示边栏",
            "showTotalBar": "显示合计栏",
            "appearance": "外观:",
            "appearanceLight": "浅色",
            "appearanceDark": "深色",
            "appearanceAuto": "自动",
            "settings.about": "关于",
            "about.documentation": "文档",
            "about.version": "版本 %@",
            "settings.aboutShort": "关于",
            "settings.updates": "更新",
            "settings.constantsUnits": "常量与单位",
            "settings.constantsUnitsShort": "常量",
            "appIcon": "应用图标：",
            "appIconDark": "深色",
            "appIconLight": "浅色",
            "operators": "运算符",
            "opPad": "运算符两侧加空格",
            "opPadCap": "1+1 变为 1 + 1",
            "opStar": "将 * 替换为 ×",
            "opStarCap": "3*3 变为 3 × 3",
            "opBacktick": "将反引号 ` 替换为 +",
            "opBacktickCap": "5`5 变为 5 + 5",
            "opQuick": "使用 QuickOperators",
            "opQuickCap": "5p5 变为 5 + 5，5m5 变为 5 − 5\n5x5 变为 5 × 5，5d5 变为 5 ÷ 5",
            "autoInsert": "自动插入",
            "autoGroup": "千位分隔符",
            "autoGroupCap": "输入时自动分组数字（10000 变为 10,000）。",
            "autoPrev": "在新行输入运算符后插入上一个答案",
            "autoPrevCap": "按回车后，输入任意运算符（+ − × 或 ÷）",
            "settings.general": "常规",
            "welcome.getStarted": "开始使用",
            "welcome.getStartedHint": "打开笔记本",
            "settings.constants": "常量",
            "constants.intro": "所有工作表均可使用。.nlx 导出不包含常量。",
            "constants.emptyTitle": "没有常量",
            "constants.emptyCap": "常量可在每个数据表中使用。.nlx 导出文件不包含常量。",
            "units.emptyTitle": "没有自定义单位",
            "units.emptyCap": "定义是 `12 feet`（现有单位的倍数）或 `new unit`（独立尺寸）。",
            "units.tab.constants": "常量",
            "units.tab.units": "单位",
            "units.intro": "所有工作表均可使用。.nlx 导出不包含单位。定义可以是 `12 feet`（现有单位的倍数）或 `new unit`（独立量纲）。",
            "units.name": "名称",
            "units.definition": "定义",
            "units.add": "添加单位",
            "units.delete": "删除单位",
            "units.newUnit": "new unit",
            "units.statusActive": "生效",
            "units.statusEmpty": "为空",
            "units.statusIncomplete": "缺少名称或定义",
            "units.statusInvalidName": "名称无效",
            "units.statusDuplicate": "名称重复",
            "units.statusBuiltIn": "名称与内置单位冲突",
            "units.statusConstant": "名称与常量冲突",
            "units.statusInvalidDefinition": "定义无效",
            "units.statusUnknown": "定义中包含未知单位",
            "units.statusCycle": "循环定义",
            "units.statusNonFinite": "定义不是正的有限数值",
            "units.statusLimit": "超过 100 个上限",
            "constants.name": "名称",
            "constants.value": "值",
            "constants.add": "添加常量",
            "constants.delete": "删除常量",
            "constants.incomplete": "缺少名称或值",
            "constants.invalidName": "名称：1–6 个单词，字母 A–Z",
            "constants.duplicate": "重名",
            "constants.reserved": "名称已保留",
            "constants.invalidExpression": "无效值",
            "constants.invalidDependency": "值含未知名称",
            "constants.cycle": "循环引用",
            "constants.exceedsLimit": "超出行数上限",
            "settings.styling": "样式",
            "settings.stylingShort": "样式",
            "settings.editing": "编辑",
            "general.interface": "界面",
            "general.notebook": "笔记本",
            "numbers.answer": "结果显示",
            "numbers.pasting": "粘贴",
            "styling.typography": "排版",
            "styling.colors": "语法颜色",
            "styling.colorsCap": "每个角色使用预设或自定义颜色。「默认」操作可恢复该角色的出厂预设。",
            "styling.colors.custom": "自定义",
            "styling.colors.default": "默认",
            "styling.colors.resetRole": "恢复此角色的默认颜色",
            "styling.colors.resetAll": "重置语法颜色",
            "styling.colors.resetAllCap": "恢复默认语法颜色。字体和答案列设置保持不变。",
            "styling.colors.pick": "为此角色选择自定义颜色",
            "roundingCap": "结果按此小数位数四舍五入。",
            "styling.fontsize": "字号:",
            "styling.font": "字体:",
            "styling.font.system": "系统默认",
            "styling.font.rounded": "圆体",
            "styling.font.serif": "衬线",
            "styling.font.monospaced": "等宽",
            "styling.color.standardText": "标准文本",
            "styling.color.cyan": "青色",
            "styling.color.green": "绿色",
            "styling.color.pinkPurple": "粉紫",
            "styling.color.blue": "蓝色",
            "styling.color.moneyPurple": "紫色",
            "styling.role.numbers": "数字",
            "styling.role.operators": "运算符",
            "styling.role.variables": "变量",
            "styling.role.units": "单位",
            "styling.role.specifiers": "连接词",
            "styling.role.headings": "标题",
            "styling.role.comments": "注释",
            "styling.role.labels": "标签",
            "styling.preview": "预览",
            "updates.group": "更新",
            "updates.checkNow": "检查更新…",
            "updates.checkNowShort": "检查",
            "updates.auto": "自动检查更新",
            "updates.autoCap": "Numlex 会在后台检查新版本，并在安装前询问。",
            "updates.unavailable": "此版本中更新不可用。",
            "updates.unavailable.notPackaged": "这是未打包的开发版本，因此更新已禁用。",
            "updates.unavailable.missingFeedURL": "此版本未配置更新源，因此更新已禁用。",
            "updates.unavailable.insecureFeedURL": "更新源地址不是安全的 HTTPS 地址，因此更新已禁用。",
            "updates.unavailable.missingPublicKey": "此版本缺少更新验证密钥，因此更新已禁用。",
            "updates.unavailable.invalidPublicKey": "此版本中的更新验证密钥无效，因此更新已禁用。",
        ],
    ]
}
