import Foundation

public struct L10n {
    public static func t(_ key: String, language: AppLanguage) -> String {
        let table = translations[language] ?? translations[.en]!
        return table[key] ?? translations[.en]![key] ?? key
    }

    public static let translations: [AppLanguage: [String: String]] = [
        .en: [
            "settings.numbers": "Numbers",
            "numbers.region": "Number format",
            "numbers.regionLabel": "Region",
            "numbers.regionCap": "How numbers are typed, pasted, grouped and displayed",
            "numbers.sample": "Example",
            "numbers.syntax": "Function arguments",
            "numbers.convertPaste": "Convert foreign numbers on paste",
            "numbers.convertPasteCap": "Paste of 1,234.56 becomes the local form, e.g. 1.234,56. Prose and already-local numbers are left untouched.",
            "numbers.grouping": "Show thousands separator",
            "numbers.groupingCap": "10000 displays as 10,000 (or the local form)",
            "numbers.compact": "Compact large numbers",
            "numbers.compactCap": "100000 displays as 100k. Copied values keep full precision.",
            "numbers.confirmTitle": "Change number format?",
            "numbers.confirmBody": "Changing the region can re-interpret the numbers in this sheet. Answers that change:",
            "numbers.apply": "Apply",
            "numbers.cancel": "Cancel",
            "sheet": "Sheet",
            "empty": "Empty",
            "line": "line",
            "lines": "lines",
            "noLines": "No lines",
            "newSheet": "New Sheet",
            "deleteSheet": "Delete sheet",
            "folderGeneral": "General",
            "newFolder": "New Folder",
            "renameFolder": "Rename Folder",
            "deleteFolder": "Delete Folder",
            "deleteFolderHelp": "The sheets in this folder are moved to General — no sheet is deleted.",
            "moveToFolder": "Move to Folder",
            "newSheetInFolder": "New Sheet in Folder",
            "dropSheetHere": "Drop a sheet here to move it",
            "folderEmpty": "No sheets",
            "sheets": "Sheets",
            "showSheets": "Show sheets",
            "hideSheets": "Hide sheets",
            "importSheet": "Import sheet (.nlx)",
            "exportSheet": "Export sheet (.nlx)",
            "enter": "Enter an expression to start",
            "settings": "Settings",
            "total": "Total",
            "copyAnswer": "Copy Answer",
            "deleteLine": "Delete Line",
            "rounding": "Rounding",
            "roundingDefault": "Default",
            "editAnswerFormatting": "Edit answer formatting",
            "decimalPlaces": "decimal places",
            "weatherUnavailable": "Weather unavailable",
            "rename": "Rename",
            "round": "Rounding numbers:",
            "fontcolor": "Font color:",
            "fontsize": "Font size:",
            "sheetname": "Sheet title:",
            "language": "Interface language:",
            "currencyRates": "Currency rates",
            "linenumber": "Line numbers:",
            "hideSidebarBtn": "Hide sidebar button when collapsed",
            "hideSidebarBtnCap": "Use ⌃⌘S (Control-Command-S) to show the sidebar",
            "appearance": "Appearance:",
            "appearanceLight": "Light",
            "appearanceDark": "Dark",
            "operators": "Operators",
            "opPad": "Pad operators with spaces",
            "opPadCap": "1+1 becomes 1 + 1",
            "opStar": "Replace * with ×",
            "opStarCap": "3*3 becomes 3 × 3",
            "opBacktick": "Replace backtick ` with +",
            "opBacktickCap": "5`5 becomes 5 + 5",
            "opQuick": "Use QuickOperators",
            "opQuickCap": "5p5 becomes 5 + 5, 5m5 becomes 5 − 5\n5x5 becomes 5 × 5, 5d5 becomes 5 ÷ 5",
            "autoInsert": "Automatic Insertions",
            "autoGroup": "Format numbers with thousand separators",
            "autoGroupCap": "Groups the numbers you type as you type (10000 becomes 10,000). How answers are grouped is a separate setting in the Numbers tab.",
            "autoPrev": "Insert previous answer after typing operator on new line",
            "autoPrevCap": "After pressing return, type any operator (+ − × or ÷)",
            "settings.general": "General",
            "settings.constants": "Constants",
            "constants.intro": "Available in every sheet. .nlx exports never embed constants.",
            "constants.name": "Name",
            "constants.value": "Value",
            "constants.add": "Add Constant",
            "constants.delete": "Delete constant",
            "constants.incomplete": "Name or value missing",
            "constants.invalidName": "Name: 1–6 words, letters A–Z",
            "constants.duplicate": "Duplicate name",
            "constants.reserved": "Name is reserved",
            "constants.invalidExpression": "Invalid value",
            "constants.invalidDependency": "Unknown name in value",
            "constants.cycle": "Circular reference",
            "constants.exceedsLimit": "Row limit reached",
            "settings.styling": "Styling",
            "settings.editing": "Editing",
            "general.interface": "Interface",
            "general.notebook": "Notebook",
            "numbers.answer": "Answer display",
            "numbers.pasting": "Pasting",
            "styling.typography": "Typography",
            "styling.colors": "Syntax colors",
            "roundingCap": "Answers are rounded to this many decimal places.",
            "linenumberCap": "Show the line number beside each input line.",
            "styling.fontsize": "Font size:",
            "styling.font": "Font:",
            "styling.font.system": "System Default",
            "styling.font.rounded": "Rounded",
            "styling.font.serif": "Serif",
            "styling.font.monospaced": "Monospaced",
            "styling.color.standardText": "Standard Text",
            "styling.color.cyan": "Cyan",
            "styling.color.green": "Green",
            "styling.color.pinkPurple": "Pink Purple",
            "styling.color.blue": "Blue",
            "styling.color.moneyPurple": "Money Purple",
            "styling.role.numbers": "Numbers",
            "styling.role.operators": "Operators",
            "styling.role.variables": "Variables",
            "styling.role.units": "Units",
            "styling.role.specifiers": "Specifiers",
            "styling.role.headings": "Headings",
            "styling.role.comments": "Comments",
            "styling.role.labels": "Labels",
            "styling.preview": "Preview",
        ],
        .ru: [
            "settings.numbers": "Числа",
            "numbers.region": "Формат чисел",
            "numbers.regionLabel": "Регион",
            "numbers.regionCap": "Как числа вводятся, вставляются, группируются и отображаются",
            "numbers.sample": "Пример",
            "numbers.syntax": "Аргументы функций",
            "numbers.convertPaste": "Преобразовать иностранные числа при вставке",
            "numbers.convertPasteCap": "Вставленное 1,234.56 станет локальной формой, например 1 234,56. Текст и локальные числа не меняются.",
            "numbers.grouping": "Показывать разделитель тысяч",
            "numbers.groupingCap": "10000 отображается как 10 000 (или в локальной форме)",
            "numbers.compact": "Компактно показывать большие числа",
            "numbers.compactCap": "100000 отображается как 100k. Скопированные значения сохраняют точность.",
            "numbers.confirmTitle": "Сменить формат чисел?",
            "numbers.confirmBody": "Смена региона может переинтерпретировать числа в этом листе. Меняющиеся ответы:",
            "numbers.apply": "Применить",
            "numbers.cancel": "Отмена",
            "sheet": "Лист",
            "empty": "Пусто",
            "line": "строка",
            "lines": "строки",
            "noLines": "Нет строк",
            "newSheet": "Новый лист",
            "deleteSheet": "Удалить лист",
            "folderGeneral": "Общие",
            "newFolder": "Новая папка",
            "renameFolder": "Переименовать папку",
            "deleteFolder": "Удалить папку",
            "deleteFolderHelp": "Листы из этой папки будут перемещены в «Общие» — ни один лист не удаляется.",
            "moveToFolder": "Переместить в папку",
            "newSheetInFolder": "Новый лист в папке",
            "dropSheetHere": "Перетащите лист сюда, чтобы переместить его",
            "folderEmpty": "Нет листов",
            "sheets": "Листы",
            "showSheets": "Показать листы",
            "hideSheets": "Скрыть листы",
            "importSheet": "Импорт листа (.nlx)",
            "exportSheet": "Экспорт листа (.nlx)",
            "enter": "Введите выражение чтобы начать",
            "settings": "Настройки",
            "total": "Итого",
            "copyAnswer": "Копировать ответ",
            "deleteLine": "Удалить строку",
            "rounding": "Округление",
            "roundingDefault": "По умолчанию",
            "editAnswerFormatting": "Изменение формата ответа",
            "decimalPlaces": "знаков после запятой",
            "weatherUnavailable": "Погода недоступна",
            "rename": "Переименовать",
            "round": "Округление чисел:",
            "fontcolor": "Цвет текста:",
            "fontsize": "Размер текста:",
            "sheetname": "Заголовок листов:",
            "language": "Язык интерфейса:",
            "currencyRates": "Курсы валют",
            "linenumber": "Номера строк",
            "hideSidebarBtn": "Скрывать кнопку боковой панели после сворачивания",
            "hideSidebarBtnCap": "Чтобы открыть боковую панель, нажмите ⌃⌘S (Control-Command-S)",
            "appearance": "Оформление:",
            "appearanceLight": "Светлое",
            "appearanceDark": "Тёмное",
            "operators": "Операторы",
            "opPad": "Отступы вокруг операторов",
            "opPadCap": "1+1 станет 1 + 1",
            "opStar": "Заменять * на ×",
            "opStarCap": "3*3 станет 3 × 3",
            "opBacktick": "Заменять обратную кавычку ` на +",
            "opBacktickCap": "5`5 станет 5 + 5",
            "opQuick": "Использовать QuickOperators",
            "opQuickCap": "5p5 станет 5 + 5, 5m5 станет 5 − 5\n5x5 станет 5 × 5, 5d5 станет 5 ÷ 5",
            "autoInsert": "Автоматические вставки",
            "autoGroup": "Разделители тысяч в числах",
            "autoGroupCap": "Группирует числа при вводе (10000 становится 10 000). Разделение ответов настраивается отдельно на вкладке «Числа».",
            "autoPrev": "Вставлять предыдущий ответ после оператора на новой строке",
            "autoPrevCap": "После нажатия Return введите оператор (+ − × или ÷)",
            "settings.general": "Основные",
            "settings.constants": "Константы",
            "constants.intro": "Доступны во всех листах. .nlx-файлы не содержат константы.",
            "constants.name": "Имя",
            "constants.value": "Значение",
            "constants.add": "Добавить константу",
            "constants.delete": "Удалить константу",
            "constants.incomplete": "Не указано имя или значение",
            "constants.invalidName": "Имя: 1–6 слов, буквы A–Z",
            "constants.duplicate": "Дублирующееся имя",
            "constants.reserved": "Имя зарезервировано",
            "constants.invalidExpression": "Недопустимое значение",
            "constants.invalidDependency": "Неизвестное имя в значении",
            "constants.cycle": "Циклическая ссылка",
            "constants.exceedsLimit": "Превышен лимит строк",
            "settings.styling": "Оформление",
            "settings.editing": "Редактирование",
            "general.interface": "Интерфейс",
            "general.notebook": "Блокнот",
            "numbers.answer": "Отображение ответов",
            "numbers.pasting": "Вставка",
            "styling.typography": "Типографика",
            "styling.colors": "Цвета синтаксиса",
            "roundingCap": "Ответы округляются до этого количества десятичных знаков.",
            "linenumberCap": "Показывать номер строки слева от каждой строки ввода.",
            "styling.fontsize": "Размер шрифта:",
            "styling.font": "Шрифт:",
            "styling.font.system": "Системный",
            "styling.font.rounded": "Округлённый",
            "styling.font.serif": "С засечками",
            "styling.font.monospaced": "Моноширинный",
            "styling.color.standardText": "Основной текст",
            "styling.color.cyan": "Бирюзовый",
            "styling.color.green": "Зелёный",
            "styling.color.pinkPurple": "Розово-фиолетовый",
            "styling.color.blue": "Синий",
            "styling.color.moneyPurple": "Фиолетовый",
            "styling.role.numbers": "Числа",
            "styling.role.operators": "Операторы",
            "styling.role.variables": "Переменные",
            "styling.role.units": "Единицы",
            "styling.role.specifiers": "Связки",
            "styling.role.headings": "Заголовки",
            "styling.role.comments": "Комментарии",
            "styling.role.labels": "Подписи",
            "styling.preview": "Предпросмотр",
        ],
        .de: [
            "settings.numbers": "Zahlen",
            "numbers.region": "Zahlenformat",
            "numbers.regionLabel": "Region",
            "numbers.regionCap": "Wie Zahlen eingegeben, eingefügt, gruppiert und angezeigt werden",
            "numbers.sample": "Beispiel",
            "numbers.syntax": "Funktionsargumente",
            "numbers.convertPaste": "Fremde Zahlen beim Einfügen umwandeln",
            "numbers.convertPasteCap": "Eingefügtes 1,234.56 wird zur lokalen Form, z. B. 1.234,56. Text und lokale Zahlen bleiben unverändert.",
            "numbers.grouping": "Tausendertrennzeichen anzeigen",
            "numbers.groupingCap": "10000 wird als 10.000 (oder lokal) angezeigt",
            "numbers.compact": "Große Zahlen kompakt anzeigen",
            "numbers.compactCap": "100000 wird als 100k angezeigt. Kopierte Werte behalten die volle Präzision.",
            "numbers.confirmTitle": "Zahlenformat ändern?",
            "numbers.confirmBody": "Die Region kann die Zahlen in diesem Blatt neu deuten. Antworten, die sich ändern:",
            "numbers.apply": "Anwenden",
            "numbers.cancel": "Abbrechen",
            "sheet": "Blatt",
            "empty": "Leer",
            "line": "Zeile",
            "lines": "Zeilen",
            "noLines": "Keine Zeilen",
            "newSheet": "Neues Blatt",
            "deleteSheet": "Blatt löschen",
            "folderGeneral": "Allgemein",
            "newFolder": "Neuer Ordner",
            "renameFolder": "Ordner umbenennen",
            "deleteFolder": "Ordner löschen",
            "deleteFolderHelp": "Die Blätter in diesem Ordner werden nach „Allgemein“ verschoben — es wird kein Blatt gelöscht.",
            "moveToFolder": "In Ordner verschieben",
            "newSheetInFolder": "Neues Blatt im Ordner",
            "dropSheetHere": "Blatt hierher ziehen, um es zu verschieben",
            "folderEmpty": "Keine Blätter",
            "sheets": "Blätter",
            "showSheets": "Blätter anzeigen",
            "hideSheets": "Blätter ausblenden",
            "importSheet": "Blatt importieren (.nlx)",
            "exportSheet": "Blatt exportieren (.nlx)",
            "enter": "Geben Sie einen Ausdruck ein, um zu beginnen",
            "settings": "Einstellungen",
            "total": "Gesamt",
            "copyAnswer": "Antwort kopieren",
            "deleteLine": "Zeile löschen",
            "rounding": "Rundung",
            "roundingDefault": "Standard",
            "editAnswerFormatting": "Antwortformat bearbeiten",
            "decimalPlaces": "Dezimalstellen",
            "weatherUnavailable": "Wetter nicht verfügbar",
            "rename": "Umbenennen",
            "round": "Rundung von Zahlen",
            "fontsize": "Schriftgröße",
            "sheetname": "Titel der Blätter:",
            "language": "Sprache der Schnittstelle:",
            "currencyRates": "Wechselkurse",
            "linenumber": "Zeilennummern:",
            "hideSidebarBtn": "Seitenleisten-Taste nach dem Einklappen ausblenden",
            "hideSidebarBtnCap": "Seitenleiste mit ⌃⌘S (Control-Command-S) einblenden",
            "appearance": "Erscheinungsbild:",
            "appearanceLight": "Hell",
            "appearanceDark": "Dunkel",
            "operators": "Operatoren",
            "opPad": "Operatoren mit Leerzeichen umgeben",
            "opPadCap": "1+1 wird 1 + 1",
            "opStar": "* durch × ersetzen",
            "opStarCap": "3*3 wird 3 × 3",
            "opBacktick": "Backtick ` durch + ersetzen",
            "opBacktickCap": "5`5 wird 5 + 5",
            "opQuick": "QuickOperators verwenden",
            "opQuickCap": "5p5 wird 5 + 5, 5m5 wird 5 − 5\n5x5 wird 5 × 5, 5d5 wird 5 ÷ 5",
            "autoInsert": "Automatische Einfügungen",
            "autoGroup": "Tausendertrennzeichen in Zahlen",
            "autoGroupCap": "Gruppiert Zahlen beim Tippen (10000 wird 10,000). Die Gruppierung der Ergebnisse wird separat im Tab „Zahlen“ festgelegt.",
            "autoPrev": "Vorherige Antwort nach Operator auf neuer Zeile einfügen",
            "autoPrevCap": "Nach Return einen Operator eingeben (+ − × oder ÷)",
            "settings.general": "Allgemein",
            "settings.constants": "Konstanten",
            "constants.intro": "In allen Blättern verfügbar. .nlx-Dateien enthalten keine Konstanten.",
            "constants.name": "Name",
            "constants.value": "Wert",
            "constants.add": "Konstante hinzufügen",
            "constants.delete": "Konstante löschen",
            "constants.incomplete": "Name oder Wert fehlt",
            "constants.invalidName": "Name: 1–6 Wörter, Buchstaben A–Z",
            "constants.duplicate": "Namensduplikat",
            "constants.reserved": "Name ist reserviert",
            "constants.invalidExpression": "Ungültiger Wert",
            "constants.invalidDependency": "Unbekannter Name im Wert",
            "constants.cycle": "Zirkulärer Bezug",
            "constants.exceedsLimit": "Zeilenlimit erreicht",
            "settings.styling": "Stil",
            "settings.editing": "Bearbeiten",
            "general.interface": "Oberfläche",
            "general.notebook": "Notizbuch",
            "numbers.answer": "Antwortanzeige",
            "numbers.pasting": "Einfügen",
            "styling.typography": "Typografie",
            "styling.colors": "Syntaxfarben",
            "roundingCap": "Ergebnisse werden auf diese Nachkommastellen gerundet.",
            "linenumberCap": "Zeigt die Zeilennummer neben jeder Eingabezeile an.",
            "styling.fontsize": "Schriftgröße:",
            "styling.font": "Schriftart:",
            "styling.font.system": "Systemschrift",
            "styling.font.rounded": "Rund",
            "styling.font.serif": "Serife",
            "styling.font.monospaced": "Monospaziert",
            "styling.color.standardText": "Standardtext",
            "styling.color.cyan": "Cyan",
            "styling.color.green": "Grün",
            "styling.color.pinkPurple": "Rosalila",
            "styling.color.blue": "Blau",
            "styling.color.moneyPurple": "Violett",
            "styling.role.numbers": "Zahlen",
            "styling.role.operators": "Operatoren",
            "styling.role.variables": "Variablen",
            "styling.role.units": "Einheiten",
            "styling.role.specifiers": "Bindewörter",
            "styling.role.headings": "Überschriften",
            "styling.role.comments": "Kommentare",
            "styling.role.labels": "Beschriftungen",
            "styling.preview": "Vorschau",
        ],
        .fr: [
            "settings.numbers": "Nombres",
            "numbers.region": "Format des nombres",
            "numbers.regionLabel": "Région",
            "numbers.regionCap": "Comment les nombres sont saisis, collés, groupés et affichés",
            "numbers.sample": "Exemple",
            "numbers.syntax": "Arguments de fonction",
            "numbers.convertPaste": "Convertir les nombres étrangers lors du collage",
            "numbers.convertPasteCap": "Un collage de 1,234.56 devient la forme locale, p. ex. 1 234,56. Le texte et les nombres locaux sont inchangés.",
            "numbers.grouping": "Afficher le séparateur de milliers",
            "numbers.groupingCap": "10000 s'affiche comme 10 000 (ou forme locale)",
            "numbers.compact": "Nombres grands en forme compacte",
            "numbers.compactCap": "100000 s'affiche comme 100k. Les valeurs copiées gardent la précision complète.",
            "numbers.confirmTitle": "Changer le format des nombres ?",
            "numbers.confirmBody": "Changer de région peut réinterpréter les nombres de cette feuille. Réponses modifiées :",
            "numbers.apply": "Appliquer",
            "numbers.cancel": "Annuler",
            "sheet": "Feuille",
            "empty": "Vide",
            "line": "ligne",
            "lines": "lignes",
            "noLines": "Aucune ligne",
            "newSheet": "Nouvelle feuille",
            "deleteSheet": "Supprimer la feuille",
            "folderGeneral": "Général",
            "newFolder": "Nouvel dossier",
            "renameFolder": "Renommer le dossier",
            "deleteFolder": "Supprimer le dossier",
            "deleteFolderHelp": "Les feuilles de ce dossier sont déplacées vers « Général » — aucune feuille n'est supprimée.",
            "moveToFolder": "Déplacer vers le dossier",
            "newSheetInFolder": "Nouvelle feuille dans le dossier",
            "dropSheetHere": "Déposez une feuille ici pour la déplacer",
            "folderEmpty": "Aucune feuille",
            "sheets": "Feuilles",
            "showSheets": "Afficher les feuilles",
            "hideSheets": "Masquer les feuilles",
            "importSheet": "Importer (.nlx)",
            "exportSheet": "Exporter (.nlx)",
            "enter": "Saisissez une expression",
            "settings": "Réglages",
            "total": "Total",
            "copyAnswer": "Copier la réponse",
            "deleteLine": "Supprimer la ligne",
            "rounding": "Arrondi",
            "roundingDefault": "Par défaut",
            "editAnswerFormatting": "Modifier le format de la réponse",
            "decimalPlaces": "décimales",
            "weatherUnavailable": "Météo indisponible",
            "rename": "Renommer",
            "round": "Arrondi:",
            "fontsize": "Taille de police:",
            "sheetname": "Titre:",
            "language": "Langue:",
            "currencyRates": "Taux de change",
            "linenumber": "Numéros de ligne:",
            "hideSidebarBtn": "Masquer le bouton de la barre latérale une fois réduite",
            "hideSidebarBtnCap": "Réafficher la barre latérale avec ⌃⌘S (Contrôle-Commande-S)",
            "appearance": "Apparence:",
            "appearanceLight": "Clair",
            "appearanceDark": "Sombre",
            "operators": "Opérateurs",
            "opPad": "Espacer les opérateurs",
            "opPadCap": "1+1 devient 1 + 1",
            "opStar": "Remplacer * par ×",
            "opStarCap": "3*3 devient 3 × 3",
            "opBacktick": "Remplacer la backtick ` par +",
            "opBacktickCap": "5`5 devient 5 + 5",
            "opQuick": "Utiliser QuickOperators",
            "opQuickCap": "5p5 devient 5 + 5, 5m5 devient 5 − 5\n5x5 devient 5 × 5, 5d5 devient 5 ÷ 5",
            "autoInsert": "Insertions automatiques",
            "autoGroup": "Séparateurs de milliers",
            "autoGroupCap": "Groupe les nombres saisis pendant la saisie (10000 devient 10 000). Le regroupement des réponses s'ajuste séparément dans l'onglet « Nombres ».",
            "autoPrev": "Insérer la réponse précédente après un opérateur sur une nouvelle ligne",
            "autoPrevCap": "Après Retour, tapez un opérateur (+ − × ou ÷)",
            "settings.general": "Général",
            "settings.constants": "Constantes",
            "constants.intro": "Disponibles dans toutes les feuilles. Les exports .nlx ne les incluent pas.",
            "constants.name": "Nom",
            "constants.value": "Valeur",
            "constants.add": "Ajouter une constante",
            "constants.delete": "Supprimer la constante",
            "constants.incomplete": "Nom ou valeur manquant",
            "constants.invalidName": "Nom : 1 à 6 mots, lettres A–Z",
            "constants.duplicate": "Nom en double",
            "constants.reserved": "Nom réservé",
            "constants.invalidExpression": "Valeur invalide",
            "constants.invalidDependency": "Nom inconnu dans la valeur",
            "constants.cycle": "Référence circulaire",
            "constants.exceedsLimit": "Limite de lignes atteinte",
            "settings.styling": "Style",
            "settings.editing": "Édition",
            "general.interface": "Interface",
            "general.notebook": "Cahier",
            "numbers.answer": "Affichage des réponses",
            "numbers.pasting": "Collage",
            "styling.typography": "Typographie",
            "styling.colors": "Couleurs de syntaxe",
            "roundingCap": "Les résultats sont arrondis à ce nombre de décimales.",
            "linenumberCap": "Affiche le numéro de ligne à gauche de chaque ligne saisie.",
            "styling.fontsize": "Taille de police:",
            "styling.font": "Police:",
            "styling.font.system": "Police système",
            "styling.font.rounded": "Arrondi",
            "styling.font.serif": "Serif",
            "styling.font.monospaced": "Monospace",
            "styling.color.standardText": "Texte standard",
            "styling.color.cyan": "Cyan",
            "styling.color.green": "Vert",
            "styling.color.pinkPurple": "Rose-violet",
            "styling.color.blue": "Bleu",
            "styling.color.moneyPurple": "Violet",
            "styling.role.numbers": "Nombres",
            "styling.role.operators": "Opérateurs",
            "styling.role.variables": "Variables",
            "styling.role.units": "Unités",
            "styling.role.specifiers": "Mots de liaison",
            "styling.role.headings": "Titres",
            "styling.role.comments": "Commentaires",
            "styling.role.labels": "Libellés",
            "styling.preview": "Aperçu",
        ],
        .it: [
            "settings.numbers": "Numeri",
            "numbers.region": "Formato numerico",
            "numbers.regionLabel": "Regione",
            "numbers.regionCap": "Come i numeri vengono digitati, incollati, raggruppati e visualizzati",
            "numbers.sample": "Esempio",
            "numbers.syntax": "Argomenti delle funzioni",
            "numbers.convertPaste": "Converti i numeri stranieri all'incollaggio",
            "numbers.convertPasteCap": "Un incolla di 1,234.56 diventa la forma locale, es. 1.234,56. Il testo e i numeri locali restano invariati.",
            "numbers.grouping": "Mostra il separatore delle migliaia",
            "numbers.groupingCap": "10000 viene visualizzato come 10.000 (o forma locale)",
            "numbers.compact": "Numeri grandi in forma compatta",
            "numbers.compactCap": "100000 viene visualizzato come 100k. I valori copiati mantengono la precisione completa.",
            "numbers.confirmTitle": "Cambiare il formato numerico?",
            "numbers.confirmBody": "La regione può ridefinire i numeri in questo foglio. Risultati che cambiano:",
            "numbers.apply": "Applica",
            "numbers.cancel": "Annulla",
            "sheet": "Foglio",
            "empty": "Vuoto",
            "line": "riga",
            "lines": "righe",
            "noLines": "Nessuna riga",
            "newSheet": "Nuovo foglio",
            "deleteSheet": "Elimina foglio",
            "folderGeneral": "Generale",
            "newFolder": "Nuova cartella",
            "renameFolder": "Rinomina cartella",
            "deleteFolder": "Elimina cartella",
            "deleteFolderHelp": "I fogli in questa cartella vengono spostati in „Generale“ — nessun foglio viene eliminato.",
            "moveToFolder": "Sposta nella cartella",
            "newSheetInFolder": "Nuovo foglio nella cartella",
            "dropSheetHere": "Rilascia un foglio qui per spostarlo",
            "folderEmpty": "Nessun foglio",
            "sheets": "Fogli",
            "showSheets": "Mostra fogli",
            "hideSheets": "Nascondi fogli",
            "importSheet": "Importa (.nlx)",
            "exportSheet": "Esporta (.nlx)",
            "enter": "Inserisci un'espressione",
            "settings": "Impostazioni",
            "total": "Totale",
            "copyAnswer": "Copia risposta",
            "deleteLine": "Elimina riga",
            "rounding": "Arrotondamento",
            "roundingDefault": "Predefinito",
            "editAnswerFormatting": "Modifica il formato della risposta",
            "decimalPlaces": "case decimali",
            "weatherUnavailable": "Meteo non disponibile",
            "rename": "Rinomina",
            "round": "Arrotondamento:",
            "fontsize": "Dimensione:",
            "sheetname": "Titolo:",
            "language": "Lingua:",
            "currencyRates": "Tassi di cambio",
            "linenumber": "Numeri di riga:",
            "hideSidebarBtn": "Nascondi il pulsante della barra laterale dopo la compressione",
            "hideSidebarBtnCap": "Mostra di nuovo la barra laterale con ⌃⌘S (Control-Comando-S)",
            "appearance": "Aspetto:",
            "appearanceLight": "Chiaro",
            "appearanceDark": "Scuro",
            "operators": "Operatori",
            "opPad": "Spaziatura intorno agli operatori",
            "opPadCap": "1+1 diventa 1 + 1",
            "opStar": "Sostituisci * con ×",
            "opStarCap": "3*3 diventa 3 × 3",
            "opBacktick": "Sostituisci backtick ` con +",
            "opBacktickCap": "5`5 diventa 5 + 5",
            "opQuick": "Usa QuickOperators",
            "opQuickCap": "5p5 diventa 5 + 5, 5m5 diventa 5 − 5\n5x5 diventa 5 × 5, 5d5 diventa 5 ÷ 5",
            "autoInsert": "Inserimenti automatici",
            "autoGroup": "Separatore delle migliaia",
            "autoGroupCap": "Raggruppa i numeri mentre digiti (10000 diventa 10.000). Il raggruppamento dei risultati si imposta separatamente nella scheda „Numeri“.",
            "autoPrev": "Inserisci la risposta precedente dopo un operatore su una nuova riga",
            "autoPrevCap": "Dopo Invio, digita un operatore (+ − × o ÷)",
            "settings.general": "Generali",
            "settings.constants": "Costanti",
            "constants.intro": "Disponibili in ogni foglio. Gli esport .nlx non includono le costanti.",
            "constants.name": "Nome",
            "constants.value": "Valore",
            "constants.add": "Aggiungi costante",
            "constants.delete": "Elimina costante",
            "constants.incomplete": "Manca nome o valore",
            "constants.invalidName": "Nome: 1–6 parole, lettere A–Z",
            "constants.duplicate": "Nome duplicato",
            "constants.reserved": "Nome riservato",
            "constants.invalidExpression": "Valore non valido",
            "constants.invalidDependency": "Nome sconosciuto nel valore",
            "constants.cycle": "Riferimento circolare",
            "constants.exceedsLimit": "Limite di righe raggiunto",
            "settings.styling": "Stile",
            "settings.editing": "Modifica",
            "general.interface": "Interfaccia",
            "general.notebook": "Quaderno",
            "numbers.answer": "Visualizzazione risposte",
            "numbers.pasting": "Incolla",
            "styling.typography": "Tipografia",
            "styling.colors": "Colori sintassi",
            "roundingCap": "I risultati vengono arrotondati a questo numero di cifre decimali.",
            "linenumberCap": "Mostra il numero di riga accanto a ogni riga di immissione.",
            "styling.fontsize": "Dimensione carattere:",
            "styling.font": "Carattere:",
            "styling.font.system": "Carattere di sistema",
            "styling.font.rounded": "Arrotondato",
            "styling.font.serif": "Serif",
            "styling.font.monospaced": "Monospazio",
            "styling.color.standardText": "Testo standard",
            "styling.color.cyan": "Ciano",
            "styling.color.green": "Verde",
            "styling.color.pinkPurple": "Rosa-viola",
            "styling.color.blue": "Blu",
            "styling.color.moneyPurple": "Viola",
            "styling.role.numbers": "Numeri",
            "styling.role.operators": "Operatori",
            "styling.role.variables": "Variabili",
            "styling.role.units": "Unità",
            "styling.role.specifiers": "Connettivi",
            "styling.role.headings": "Titoli",
            "styling.role.comments": "Commenti",
            "styling.role.labels": "Etichette",
            "styling.preview": "Anteprima",
        ],
        .zh: [
            "settings.numbers": "数字",
            "numbers.region": "数字格式",
            "numbers.regionLabel": "地区",
            "numbers.regionCap": "数字的输入、粘贴、分组与显示方式",
            "numbers.sample": "示例",
            "numbers.syntax": "函数参数",
            "numbers.convertPaste": "粘贴时转换外来数字",
            "numbers.convertPasteCap": "粘贴的 1,234.56 会变为本地形式，例如 1.234,56。文本和本地数字保持不变。",
            "numbers.grouping": "显示千位分隔符",
            "numbers.groupingCap": "10000 显示为 10,000（或本地形式）",
            "numbers.compact": "紧凑显示大数字",
            "numbers.compactCap": "100000 显示为 100k。复制的值保留完整精度。",
            "numbers.confirmTitle": "更改数字格式？",
            "numbers.confirmBody": "更改地区可能重新解释本表中的数字。发生变化的结果：",
            "numbers.apply": "应用",
            "numbers.cancel": "取消",
            "sheet": "工作表",
            "empty": "空",
            "line": "行",
            "lines": "行",
            "noLines": "无行",
            "newSheet": "新建工作表",
            "deleteSheet": "删除工作表",
            "folderGeneral": "常规",
            "newFolder": "新建文件夹",
            "renameFolder": "重命名文件夹",
            "deleteFolder": "删除文件夹",
            "deleteFolderHelp": "该文件夹中的工作表会移到“常规”，不会删除任何工作表。",
            "moveToFolder": "移动到文件夹",
            "newSheetInFolder": "在文件夹中新建工作表",
            "dropSheetHere": "将工作表拖放到此处以移动",
            "folderEmpty": "没有工作表",
            "sheets": "工作表",
            "showSheets": "显示工作表",
            "hideSheets": "隐藏工作表",
            "importSheet": "导入 (.nlx)",
            "exportSheet": "导出 (.nlx)",
            "enter": "输入表达式开始",
            "settings": "设置",
            "total": "总计",
            "copyAnswer": "复制答案",
            "deleteLine": "删除行",
            "rounding": "舍入",
            "roundingDefault": "默认",
            "editAnswerFormatting": "编辑答案格式",
            "decimalPlaces": "小数位",
            "weatherUnavailable": "天气不可用",
            "rename": "重命名",
            "round": "小数位:",
            "fontsize": "字号:",
            "sheetname": "标题:",
            "language": "语言:",
            "currencyRates": "货币汇率",
            "linenumber": "行号:",
            "hideSidebarBtn": "收起后隐藏边栏按钮",
            "hideSidebarBtnCap": "使用 ⌃⌘S (Control-Command-S) 显示边栏",
            "appearance": "外观:",
            "appearanceLight": "浅色",
            "appearanceDark": "深色",
            "operators": "运算符",
            "opPad": "运算符两侧加空格",
            "opPadCap": "1+1 变为 1 + 1",
            "opStar": "将 * 替换为 ×",
            "opStarCap": "3*3 变为 3 × 3",
            "opBacktick": "将反引号 ` 替换为 +",
            "opBacktickCap": "5`5 变为 5 + 5",
            "opQuick": "使用 QuickOperators",
            "opQuickCap": "5p5 变为 5 + 5，5m5 变为 5 − 5\n5x5 变为 5 × 5，5d5 变为 5 ÷ 5",
            "autoInsert": "自动插入",
            "autoGroup": "千位分隔符",
            "autoGroupCap": "输入时自动分组数字（10000 变为 10,000）。答案的分组在“数字”标签页中单独设置。",
            "autoPrev": "在新行输入运算符后插入上一个答案",
            "autoPrevCap": "按回车后，输入任意运算符（+ − × 或 ÷）",
            "settings.general": "常规",
            "settings.constants": "常量",
            "constants.intro": "所有工作表均可使用。.nlx 导出不包含常量。",
            "constants.name": "名称",
            "constants.value": "值",
            "constants.add": "添加常量",
            "constants.delete": "删除常量",
            "constants.incomplete": "缺少名称或值",
            "constants.invalidName": "名称：1–6 个单词，字母 A–Z",
            "constants.duplicate": "重名",
            "constants.reserved": "名称已保留",
            "constants.invalidExpression": "无效值",
            "constants.invalidDependency": "值含未知名称",
            "constants.cycle": "循环引用",
            "constants.exceedsLimit": "超出行数上限",
            "settings.styling": "样式",
            "settings.editing": "编辑",
            "general.interface": "界面",
            "general.notebook": "笔记本",
            "numbers.answer": "结果显示",
            "numbers.pasting": "粘贴",
            "styling.typography": "排版",
            "styling.colors": "语法颜色",
            "roundingCap": "结果按此小数位数四舍五入。",
            "linenumberCap": "在每行输入旁显示行号。",
            "styling.fontsize": "字号:",
            "styling.font": "字体:",
            "styling.font.system": "系统默认",
            "styling.font.rounded": "圆体",
            "styling.font.serif": "衬线",
            "styling.font.monospaced": "等宽",
            "styling.color.standardText": "标准文本",
            "styling.color.cyan": "青色",
            "styling.color.green": "绿色",
            "styling.color.pinkPurple": "粉紫",
            "styling.color.blue": "蓝色",
            "styling.color.moneyPurple": "紫色",
            "styling.role.numbers": "数字",
            "styling.role.operators": "运算符",
            "styling.role.variables": "变量",
            "styling.role.units": "单位",
            "styling.role.specifiers": "连接词",
            "styling.role.headings": "标题",
            "styling.role.comments": "注释",
            "styling.role.labels": "标签",
            "styling.preview": "预览",
        ],
    ]
}
