import Foundation

public struct L10n {
    public static func t(_ key: String, language: AppLanguage) -> String {
        let table = translations[language] ?? translations[.en]!
        return table[key] ?? translations[.en]![key] ?? key
    }

    public static let translations: [AppLanguage: [String: String]] = [
        .en: [
            "sheet": "Sheet",
            "empty": "Empty",
            "line": "line",
            "lines": "lines",
            "noLines": "No lines",
            "newSheet": "New sheet",
            "deleteSheet": "Delete sheet",
            "sheets": "Sheets",
            "showSheets": "Show sheets",
            "hideSheets": "Hide sheets",
            "importSheet": "Import sheet (.nlx)",
            "exportSheet": "Export sheet (.nlx)",
            "enter": "Enter an expression to start",
            "settings": "Settings",
            "total": "Total",
            "rename": "Rename",
            "round": "Rounding numbers:",
            "fontcolor": "Font color:",
            "fontsize": "Font size:",
            "sheetname": "Sheet title:",
            "language": "Interface language:",
            "linenumber": "Line numbers:",
        ],
        .ru: [
            "sheet": "Лист",
            "empty": "Пусто",
            "line": "строка",
            "lines": "строки",
            "noLines": "Нет строк",
            "newSheet": "Новый лист",
            "deleteSheet": "Удалить лист",
            "sheets": "Листы",
            "showSheets": "Показать листы",
            "hideSheets": "Скрыть листы",
            "importSheet": "Импорт листа (.nlx)",
            "exportSheet": "Экспорт листа (.nlx)",
            "enter": "Введите выражение чтобы начать",
            "settings": "Настройки",
            "total": "Итого",
            "rename": "Переименовать",
            "round": "Округление чисел:",
            "fontcolor": "Цвет текста:",
            "fontsize": "Размер текста:",
            "sheetname": "Заголовок листов:",
            "language": "Язык интерфейса:",
            "linenumber": "Номера строк",
        ],
        .de: [
            "sheet": "Blatt",
            "empty": "Leer",
            "line": "Zeile",
            "lines": "Zeilen",
            "noLines": "Keine Zeilen",
            "newSheet": "Neues Blatt",
            "deleteSheet": "Blatt löschen",
            "sheets": "Blätter",
            "showSheets": "Blätter anzeigen",
            "hideSheets": "Blätter ausblenden",
            "importSheet": "Blatt importieren (.nlx)",
            "exportSheet": "Blatt exportieren (.nlx)",
            "enter": "Geben Sie einen Ausdruck ein, um zu beginnen",
            "settings": "Einstellungen",
            "total": "Gesamt",
            "rename": "Umbenennen",
            "round": "Rundung von Zahlen",
            "fontsize": "Schriftgröße",
            "sheetname": "Titel der Blätter:",
            "language": "Sprache der Schnittstelle:",
            "linenumber": "Zeilennummern:",
        ],
        .fr: [
            "sheet": "Feuille",
            "empty": "Vide",
            "line": "ligne",
            "lines": "lignes",
            "noLines": "Aucune ligne",
            "newSheet": "Nouvelle feuille",
            "deleteSheet": "Supprimer la feuille",
            "sheets": "Feuilles",
            "showSheets": "Afficher les feuilles",
            "hideSheets": "Masquer les feuilles",
            "importSheet": "Importer (.nlx)",
            "exportSheet": "Exporter (.nlx)",
            "enter": "Saisissez une expression",
            "settings": "Réglages",
            "total": "Total",
            "rename": "Renommer",
            "round": "Arrondi:",
            "fontsize": "Taille de police:",
            "sheetname": "Titre:",
            "language": "Langue:",
            "linenumber": "Numéros de ligne:",
        ],
        .it: [
            "sheet": "Foglio",
            "empty": "Vuoto",
            "line": "riga",
            "lines": "righe",
            "noLines": "Nessuna riga",
            "newSheet": "Nuovo foglio",
            "deleteSheet": "Elimina foglio",
            "sheets": "Fogli",
            "showSheets": "Mostra fogli",
            "hideSheets": "Nascondi fogli",
            "importSheet": "Importa (.nlx)",
            "exportSheet": "Esporta (.nlx)",
            "enter": "Inserisci un'espressione",
            "settings": "Impostazioni",
            "total": "Totale",
            "rename": "Rinomina",
            "round": "Arrotondamento:",
            "fontsize": "Dimensione:",
            "sheetname": "Titolo:",
            "language": "Lingua:",
            "linenumber": "Numeri di riga:",
        ],
        .zh: [
            "sheet": "工作表",
            "empty": "空",
            "line": "行",
            "lines": "行",
            "noLines": "无行",
            "newSheet": "新建工作表",
            "deleteSheet": "删除工作表",
            "sheets": "工作表",
            "showSheets": "显示工作表",
            "hideSheets": "隐藏工作表",
            "importSheet": "导入 (.nlx)",
            "exportSheet": "导出 (.nlx)",
            "enter": "输入表达式开始",
            "settings": "设置",
            "total": "总计",
            "rename": "重命名",
            "round": "小数位:",
            "fontsize": "字号:",
            "sheetname": "标题:",
            "language": "语言:",
            "linenumber": "行号:",
        ],
    ]
}
