#!/bin/bash
# Package .build/Numlex.app into a styled, compressed, read-only DMG.
#
# Output: dist/Numlex-<VERSION>-macOS-<arch>.dmg
#   - volume name "Numlex <VERSION>"
#   - contains ONLY Numlex.app plus an Applications symlink
#   - styled: Retina .background/ (1x + 2x, tiffutil -cathidpicheck),
#     volume icon from the app's AppIcon.icns, and a Finder .DS_Store
#     layout applied via Finder Apple events (Scripts/configure-dmg-finder.sh)
#   - UDZO compressed, read-only
#
# Pipeline (styled): stage a read-write HFS+ image -> attach (default
# /Volumes mount so Finder tracks it) -> copy app + symlink -> install
# .background/ (1x + 2x PNG pair = native Retina) + .VolumeIcon.icns ->
# Finder layout -> detach -> convert to UDZO.
#
# NUMLEX_PLAIN_DMG=1: skip all styling (no Finder session needed) and emit
# dist/Numlex-<VERSION>-macOS-<arch>-plain.dmg via the classic
# `hdiutil create -srcfolder` path.
#
# By default the release app is (re)built via Scripts/build-app.sh.
# Set NUMLEX_USE_BUILT_APP=1 to explicitly consume the already-built
# .build/Numlex.app without rebuilding (no stale-ambiguity: the app
# must exist; the version is always derived from its packaged plist).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_DIR="$ROOT/.build/Numlex.app"
DIST_DIR="$ROOT/dist"
CONFIGURE="$ROOT/Scripts/configure-dmg-finder.sh"
PLAIN="${NUMLEX_PLAIN_DMG:-0}"
ARCH="$(uname -m)"

if [[ "${NUMLEX_USE_BUILT_APP:-0}" == "1" ]]; then
  if [[ ! -d "$APP_DIR" ]]; then
    echo "NUMLEX_USE_BUILT_APP=1 but $APP_DIR does not exist" >&2
    exit 1
  fi
  echo "Consuming existing $APP_DIR (NUMLEX_USE_BUILT_APP=1)"
else
  bash "$ROOT/Scripts/build-app.sh" release
fi

# Version is the single source of truth from the packaged app plist.
VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$APP_DIR/Contents/Info.plist")"

TMP="$(mktemp -d /tmp/numlex-dmg.XXXXXX)"
MNT=""
cleanup() {
  local rc=$?
  if [[ -n "$MNT" ]] && mount | grep -q " on $MNT "; then
    hdiutil detach "$MNT" -quiet 2>/dev/null || true
  fi
  rm -rf "$TMP"
  exit $rc
}
trap cleanup EXIT

echo "Staging DMG content at $TMP/stage..."
STAGE="$TMP/stage"
mkdir -p "$STAGE"
cp -R "$APP_DIR" "$STAGE/Numlex.app"
ln -s /Applications "$STAGE/Applications"

mkdir -p "$DIST_DIR"
VOLNAME="Numlex $VERSION"

if [[ "$PLAIN" == "1" ]]; then
  # Unstyled fallback: classic one-shot read-only DMG from the stage dir.
  DMG_NAME="Numlex-${VERSION}-macOS-${ARCH}-plain.dmg"
  echo "NUMLEX_PLAIN_DMG=1: creating unstyled read-only UDZO $DIST_DIR/$DMG_NAME..."
  hdiutil create \
    -volname "$VOLNAME" \
    -srcfolder "$STAGE" \
    -ov \
    -format UDZO \
    -fs HFS+ \
    "$DIST_DIR/$DMG_NAME"
  echo "Done (PLAIN): $DIST_DIR/$DMG_NAME"
  ls -lh "$DIST_DIR/$DMG_NAME"
  exit 0
fi

# Styled pipeline requires a live Finder session (the layout is applied with
# real Finder Apple events). Fail clearly instead of producing a DMG whose
# .DS_Store will be regenerated by a later Finder launch.
if ! pgrep -x Finder >/dev/null 2>&1; then
  echo "error: no Finder session found; a styled DMG requires Finder." >&2
  echo "hint: run in a GUI session, or set NUMLEX_PLAIN_DMG=1 for an unstyled DMG." >&2
  exit 1
fi
if [[ ! -x "$CONFIGURE" ]]; then
  echo "error: $CONFIGURE is missing; the styled pipeline cannot apply the Finder layout." >&2
  exit 1
fi

# --- 1) Read-write HFS+ image ---------------------------------------------
# Size = staged content (dominated by the app) + headroom for .background,
# .DS_Store and the volume icon.
STAGE_KB="$(du -sk "$STAGE" | cut -f1)"
SIZE_M=$(( (STAGE_KB / 1024) + 96 ))
if (( SIZE_M < 256 )); then SIZE_M=256; fi

RW_IMG="$TMP/rw"
echo "Creating read-write HFS+ image ($SIZE_M m, volume '$VOLNAME')..."
hdiutil create \
  -size "${SIZE_M}m" \
  -fs HFS+ \
  -volname "$VOLNAME" \
  -quiet \
  -o "$RW_IMG"

# --- 2) Attach and populate -------------------------------------------------
# Attach at the default /Volumes location (Finder only tracks volumes there);
# the default mount point is deterministic: /Volumes/<volume name>.
if [[ -d "/Volumes/$VOLNAME" ]]; then
  echo "Ejecting pre-existing /Volumes/$VOLNAME ..."
  hdiutil detach "/Volumes/$VOLNAME" -quiet || true
  sleep 1
fi
echo "Attaching for styling..."
hdiutil attach -readwrite -nobrowse -noverify "$RW_IMG.dmg" -quiet
MNT="/Volumes/$VOLNAME"
if [[ ! -d "$MNT" ]]; then
  echo "error: volume did not mount at $MNT" >&2
  exit 1
fi

ditto "$STAGE/Numlex.app" "$MNT/Numlex.app"
ln -s /Applications "$MNT/Applications"

# --- 3) Retina background (1x + 2x PNG pair, native Finder hidpi) ----------
# A PNG @2x pair is Finder's native Retina background mechanism; this
# toolchain's tiffutil cannot convert PNG->TIFF, so no tiffutil step is used.
BG_DIR="$MNT/.background"
mkdir -p "$BG_DIR"
echo "Installing Retina background (1x + 2x PNG pair)..."
cp "$ROOT/Assets/DMG/NumlexDMGBackground.png" "$BG_DIR/background.png"
cp "$ROOT/Assets/DMG/NumlexDMGBackground@2x.png" "$BG_DIR/background@2x.png"
# Lossless-quality JPEG of the 2x canvas: fallback for macOS versions whose
# Finder cannot coerce the PNG into the background-picture alias.
sips -s format jpeg -s formatOptions 100 \
  "$ROOT/Assets/DMG/NumlexDMGBackground@2x.png" \
  --out "$BG_DIR/background@2x.jpg" >/dev/null

# --- 4) Volume icon (the app's icon; hidden via creator bit when available)
ICNS_SRC="$ROOT/Sources/NumlexApp/Resources/AppIcon.icns"
if [[ -f "$ICNS_SRC" ]]; then
  cp "$ICNS_SRC" "$MNT/.VolumeIcon.icns"
  if command -v SetFile >/dev/null 2>&1; then
    SetFile -a C "$MNT/.VolumeIcon.icns" 2>/dev/null || true
  fi
fi

# --- 5) Finder layout (real Finder Apple events) ----------------------------
echo "Applying Finder layout via $CONFIGURE ..."
bash "$CONFIGURE" "$MNT"

# --- 6) Detach and compress to read-only UDZO -------------------------------
hdiutil detach "$MNT" -quiet
MNT=""

DMG_NAME="Numlex-${VERSION}-macOS-${ARCH}.dmg"
echo "Converting to read-only UDZO $DIST_DIR/$DMG_NAME..."
hdiutil convert "$RW_IMG.dmg" -format UDZO -ov -o "$DIST_DIR/$DMG_NAME" -quiet
hdiutil verify "$DIST_DIR/$DMG_NAME" >/dev/null

echo "Done: $DIST_DIR/$DMG_NAME"
ls -lh "$DIST_DIR/$DMG_NAME"
